### ISSUE TITLE
Luadocs

### ISSUE THREAD

**Issue by saleweaver** [loki79uk/FS25_UniversalAutoload#1]
Hi there!

Are you working on this already, and do you need help? I haven't found the luadocs for 25, did you?

**Comment by Lennart-1337** [comment]
The docs aren't out yet

**Comment by loki79uk** [comment]
Yes, I am working on UAL as my main focus now.  I don't know how long, I'm aiming for a first ModHub release before Christmas, hopefully sooner for a working version.

No documentation yet I'm afraid, back to the old school methods of hooking functions and manually inspecting the inputs and outputs..

**Comment by loki79uk** [comment]
Closing for housekeeping
