### ISSUE TITLE
MERLOT UNLOAD

### ISSUE THREAD

**Issue by Rayman025** [loki79uk/FS25_UniversalAutoload#100]
Hey,

We can't unload from the merlot. Only with tractor/truck.

Bye

**Comment by loki79uk** [comment]
Can you please make sure your are using the latest version (v0.0.0.17) and then if still not working attach your log file to this bug.

**Comment by loki79uk** [comment]
Closing as duplicate of https://github.com/loki79uk/FS25_UniversalAutoload/issues/94
