### ISSUE TITLE
Not working on Mac M1 - (Sequoia 15.1) 

### ISSUE THREAD

**Issue by tomaklod** [loki79uk/FS25_UniversalAutoload#101]
I try to launch it on my Mac Studio M1, it doesn't appear when i try to setup a new game, but i can see it on my "modhub / installed" mods. 

It look like this when my friend play on his server : 
![image](https://github.com/user-attachments/assets/e022b627-1b79-4af2-9ee3-c3080d115cbb)

**Comment by loki79uk** [comment]
Where was it downloaded from?  Does it work in single player?

Get the latest one here:
https://github.com/loki79uk/FS25_UniversalAutoload/releases/latest/download/FS25_UniversalAutoload.zip
