### ISSUE TITLE
UAL Configs directly in vehicle XML possible again?

### ISSUE THREAD

**Issue by Mach1-Andy** [loki79uk/FS25_UniversalAutoload#102]
Hello, first of all a big thank you. That UAL is coming back.

I have a question, will it be possible again to insert specially customised areas in a UAL Config in the vehicle XML itself?

It was possible in this form in FS22. Is this planned again?

`<universalAutoLoad>
        <vehicleConfigurations title="$l10n_config_ual">
            <vehicleConfiguration name="$l10n_ui_no" />
			<vehicleConfiguration name="$l10n_ui_yes" >
                <loadingArea offset="0 0.650 -0.895" width="2.00" height="2.20" length="4.25"/>
				<options noLoadingIfUnfolded="false" enableRearLoading="true" enableSideLoading="true" isBaleTrailer="true"/>
            </vehicleConfiguration>
        </vehicleConfigurations>
    </universalAutoLoad>`

**Comment by loki79uk** [comment]
I have not decided yet.  If I do add it, then the format will be a bit different to match changes in the settings xml.  It caused me a lot of bug reports before when mods were badly set up and then autoload didn't work properly.

**Comment by Mach1-Andy** [comment]
Thank you for your answer. I hope it will be added again. I would like to use it again. I never had any problems with it but understand it well. If it should stop coming.

**Comment by loki79uk** [comment]
I'm currently thinking that this is just an extra layer of complication in which settings to use.  I have still got to decide if we save settings globally, or per vehicle per savegame.  I'll close this bug for now as not planned, but I might change my mind later when I run out of other features to add.
