### ISSUE TITLE
automatic bale mode

### ISSUE THREAD

**Issue by VikingStreaming** [loki79uk/FS25_UniversalAutoload#103]
I've tried using every bale trailer and flatbed trailer. But everytime I try to use the automatic bale mode, it does not work for me. I can load the bales using left shift + R key, but then I have to  press the keys every times I want to load a bale.

**Comment by loki79uk** [comment]
Did you delete or clear your config file before re-buying it?  Check in your settings xml that is has the bale trailer option added, e.g.:
```xml
        <vehicle configFileName="data/vehicles/brantner/dd24073/dd24073.xml">
            <configuration selectedConfigs="1">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="-0.000 1.419 -0.765" width="2.295594" length="7.304591" height="2.299080"/>
            </configuration>
        </vehicle>
 ```
 
 When configured correctly you will get CTRL-SHIFT-R for bale collection, as well as the usual SHIFT-R.
![image](https://github.com/user-attachments/assets/7d4df4b6-f1b6-4116-bd51-f252a8231b34)

**Comment by macmanluke** [comment]
I have a similar issue with the lode king flatbed - can not get the autoload option to show up no matter config changes etc
Shift-R works but thats slow

**Comment by loki79uk** [comment]
> I have a similar issue with the lode king flatbed - can not get the autoload option to show up no matter config changes etc Shift-R works but thats slow

Can you attach your mod settings file?

**Comment by macmanluke** [comment]
`<?xml version="1.0" encoding="utf-8" standalone="no"?>
<universalAutoload>
    <vehicleConfigurations>
        <vehicle configFileName="data/vehicles/lodeKing/renownTriAxleBeavertailLowDrop/renownTriAxleBeavertailLowDrop.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.013 1.568 6.242" width="3.121278" length="3.325667" height="4.083232"/>
                <loadingArea offset="0.012 0.883 -1.779" width="3.103905" length="12.712765" height="4.778553"/>
                <options isBaleTrailer="true" horizontalLoading="true"/>
            </configuration>
        </vehicle>
    </vehicleConfigurations>
</universalAutoload>
`

**Comment by loki79uk** [comment]
> Attached - renamed to .txt so it would let me upload
I guess you have a keybindings issue?

The bale collection button shows up and works for me:
![image](https://github.com/user-attachments/assets/7cdede7b-7492-4ef3-8c59-3aada9a4a69c)
![image](https://github.com/user-attachments/assets/ecaf3724-6a20-4f1f-b893-9871cd11dbc9)

**Comment by macmanluke** [comment]
Had default configs / bindings
Was bound to left shift, control R but rebound to the same and now it works

**Comment by loki79uk** [comment]
> Had default configs / bindings Was bound to left shift, control R but rebound to the same and now it works

Glad it is working now.  I think there are still some bugs with the keybinding system.  Hopefully GIANTS will sort it soon.  If you don't have any custom keybinds, then resetting from the menu sometimes solves it.  Of course back up the old file or be prepared to set any different keys again!
