### ISSUE TITLE
Question about the wood

### ISSUE THREAD

**Issue by MoneyNitch** [loki79uk/FS25_UniversalAutoload#105]
Hello,

I know the mod is still in progress, but wanted to ask if the support with tree trunks is still coming? 

At least it doesn't work yet to collect wood, both in single player and multiplayer

**Comment by 17goesfast** [comment]
I am waiting too!  Loki has mentioned many times wood autoload is coming, but there are other items to come first.

**Comment by onetaps** [comment]
To be closed. This one has already been answered multiple times f.e. in #61 #97 #45 
P.s. I'm waiting too ;)

**Comment by loki79uk** [comment]
I mean, it kind of loads at the moment.. 
![image](https://github.com/user-attachments/assets/54a69c69-4560-48aa-a957-05d9764435a1)

**Comment by MoneyNitch** [comment]
I mainly only tested the forest trailers. 

I'm closing this one. More info on the topic can be found in post #61 #97 #45
