### ISSUE TITLE
Option to toggle vertical/horizontal is not shown in a current savegame

### ISSUE THREAD

**Issue by rarandab** [loki79uk/FS25_UniversalAutoload#109]
I've tried this again with the latest version available (0.1.0.1).

If I open a new save game and buy a vehicle con autoload enabled I see the option to enable horizontal/vertical loading, but if I try it in a my savegame that option is not shown but the autoloading works ok (always in vertical).

The only mod enabled in the tests was the autoload one

[log.txt](https://github.com/user-attachments/files/18077102/log.txt)

**Comment by loki79uk** [comment]
This sounds like another key-bindings issue.  Try temporarily binding those keys to something else, or the nuclear option is to reset your keybindings from the game menu.

**Comment by rarandab** [comment]
I've donde that, removing from "inputBindings.xml" all assignemnts of universalAutoload and reconfigured it (now shows with "Insert" as default for the toggle).

Also tried changing the assignments.

But happens the same inside that savegame.

**Comment by loki79uk** [comment]
Can you zip and send me the problem savegame, and you mod settings file too?

**Comment by rarandab** [comment]
Yes, 

This is the "modSettings/UniversalAutoload.xml":
```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<universalAutoload>
    <vehicleConfigurations>
        <vehicle configFileName="data/vehicles/lizard/multiPurposeTruck/multiPurposeTruck.xml">
            <configuration selectedConfigs="1">
                <loadingArea offset="-0.000 0.958 -0.959" width="1.853746" length="3.582794" height="1.792488"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/stema/trius/trius.xml">
            <configuration selectedConfigs="1">
                <loadingArea offset="-0.000 0.780 -0.021" width="2.021258" length="4.016036" height="1.836044"/>
            </configuration>
        </vehicle>
    </vehicleConfigurations>
</universalAutoload>
```

And this is the save game [savegame1.zip](https://github.com/user-attachments/files/18080851/savegame1.zip)

**Comment by loki79uk** [comment]
It works for me:
![image](https://github.com/user-attachments/assets/d5c54537-77d7-4c11-87aa-faf4ba0eb50f)
![image](https://github.com/user-attachments/assets/f9f25d77-1f88-4818-85a3-cf84d13f49d5)


but I didn't download these mods:
![image](https://github.com/user-attachments/assets/c0fad75e-3a1a-43cd-88ce-6a7c85eedc22)

**Comment by rarandab** [comment]
Thnx, I will keep trying to identify where can be the problem...

**Comment by loki79uk** [comment]
After chatting on Discord it turns out this was resolved by resetting the keybindings AND disabling Steam Cloud Sync which was otherwise reverting the changes.
