### ISSUE TITLE
Wooden Logs

### ISSUE THREAD

**Issue by cwhandersen** [loki79uk/FS25_UniversalAutoload#110]
Hey
Great mod so far. Awesome improvements over the FS22 version.
Are you waiting with adding Wood Log loading to the mod?
If so, do you have any idea when you will be adding this feature?

Thanks for a great mod.

**Comment by asundrus** [comment]
> Hey Great mod so far. Awesome improvements over the FS22 version. Are you waiting with adding Wood Log loading to the mod? If so, do you have any idea when you will be adding this feature?
> 
> Thanks for a great mod.

Try have another read on the frontpage.

**Comment by onetaps** [comment]
Hi, this one has already been answered several times before in #45 #61 #97 #105 
I believe there is no date set when this one is coming

**Comment by loki79uk** [comment]
> Hi, this one has already been answered several times before in #45 #61 #97 #105 I believe there is no date set when this one is coming

Maybe sooner than I thought..
![image](https://github.com/user-attachments/assets/c9454dde-966b-4195-bd87-65a85e0559cd)

but there are still some bugs to iron out

**Comment by cwhandersen** [comment]
Ohhh okay. Looking great

**Comment by loki79uk** [comment]
Getting better..  This is a workaround compared to the FS22 algotithm, because the overlapBox function is unuesable now..

![image](https://github.com/user-attachments/assets/dbe079d6-34d9-4562-8323-ad37b125d013)

**Comment by onetaps** [comment]
> Getting better.. This is a workaround compared to the FS22 algotithm, because the overlapBox function is unuesable now..

Looks great tbh :) Awesome progress I'd say!
Any chance of getting that in the upcoming release or still to early to have that? :)

**Comment by loki79uk** [comment]
> Looks great tbh :) Awesome progress I'd say! Any chance of getting that in the upcoming release or still to early to have that? :)

I'm hoping to release this evening, but some other stuff to tidy up first
