### ISSUE TITLE
Unable to install mod.

### ISSUE THREAD

**Issue by romerocox** [loki79uk/FS25_UniversalAutoload#111]
![image](https://github.com/user-attachments/assets/a4f0a089-795b-4055-849c-37a716e69c6e)

Hello and thank you for the MOD.

I'm unable to install this mod, I'm using verygames server:
![image](https://github.com/user-attachments/assets/446cf59f-8eef-4b8a-ad00-0bc8c3f8203e)

Game is Farming Simulator 25 (1.3.0.0)

Any inputs would be much appreciated.

**Comment by loki79uk** [comment]
Sorry, I have no idea about this one.  The last time I saw this was because the name had a space in it, but this looks correct.  Make sure the zips are identical.  Download again from GitHub, not some other site, and put the exact same file on your computer and the server.

**Comment by loki79uk** [comment]
> So it looks like we need to manually install it.
> 
> Now, I was able to load it in-game, but I keep getting " nothing to load " for some reason, still trying to get it to work

Multiplayer is still not officially supported yet.  You need to restart after buying a vehicle in MP.  See: https://github.com/loki79uk/FS25_UniversalAutoload/issues/69

**Comment by GamingMix0** [comment]
I don't want to say anything but on my dedicated server, i.e. multiplayer, everything is running well but I only use the Krone trailer for pallets

**Comment by loki79uk** [comment]
I have my own local dedicated server (not rented), and I have never had any problems (other than #69)

**Comment by GamingMix0** [comment]
ah ok that's great, I have my own and a rented dedicated server =)

well, problems can always arise, whether expected or unexpected, for some everything goes well and for others not so well
