### ISSUE TITLE
Issue with Loading Logs

### ISSUE THREAD

**Issue by Keentin** [loki79uk/FS25_UniversalAutoload#115]
Hello Loki!

First of all, I want to thank you for your work! It’s really amazing!

Secondly, I’m reaching out because I’m facing an issue following the latest changelog. It’s impossible to load logs onto the trailer, and moreover, no trailer is working anymore... (Bales, pallets, etc.)

I’ve sold it, bought it again, restarted my server, etc... but nothing works!

I’m on a VeryGames server.
Could you help me?

Thank you!
Have a great day!

![2300320_10](https://github.com/user-attachments/assets/60a01c89-8057-475a-bde4-d91dbaa121bb)
![2300320_9](https://github.com/user-attachments/assets/c2b15869-a73f-4ad3-ac0b-e65acbd4eefd)
![2300320_7](https://github.com/user-attachments/assets/2ad70a31-8b37-4e8d-a900-c482c7970885)

**Comment by loki79uk** [comment]
If possible can you attach your server log, client log and server mod settings file?

**Comment by Keentin** [comment]
Yes, of course! Where can I find all of that?

**Comment by Keentin** [comment]
[log_2024-12-11_12-26-41.txt](https://github.com/user-attachments/files/18095958/log_2024-12-11_12-26-41.txt)
[log.txt](https://github.com/user-attachments/files/18095959/log.txt)

It looks like I’ve found the server log and client log. Is that correct?
I also found a file named 'UniversalAutoload.xml' on the server in the 'modSettings' folder.

Is that the right one?

**Comment by loki79uk** [comment]
that is the correct file - does it have any vehicle settings written in there?  The log files look fine, so if you restarted the server there must be something wrong with that file.

**Comment by Keentin** [comment]
I don't quite understand your question, but I haven't changed anything regarding the vehicle.
I don't have any mods that aren't from the official Farming Simulator 2025 'ModsHub' website.
Except yours, haha!

I'm available if you need anything, feel free to ask me questions or tests to run.

I'd be happy to help.

**Comment by Keentin** [comment]
Hello!

I saw that my issue should have been resolved in the latest changelog.
However, you mention:

NOTE: A reminder to remove any previous settings for log trailers (or bale trailers) from your mod settings file if you had previously bought and configured them before v0.2.0.0

How do I do that?

**Comment by Keentin** [comment]
Alright! And should I delete it completely?
[UniversalAutoload.txt](https://github.com/user-attachments/files/18111708/UniversalAutoload.txt)
Here is the XML file, I’ve saved it as a TXT.

**Comment by loki79uk** [comment]
> Alright! And should I delete it completely? [UniversalAutoload.txt](https://github.com/user-attachments/files/18111708/UniversalAutoload.txt) Here is the XML file, I’ve saved it as a TXT.

No need to delete - PittsTrailers and Riedler are both set as log trailers.  Are those the ones you are using?  Have you tried restarted the server, or sold and bought them again?

From the screnshots, the issue may just be that your trees are not logs but large branchs too large to fit into the trailer.  Can you try in single player so that you can look at the debugging view?

**Comment by Keentin** [comment]
While waiting for your message, I deleted the file, restarted the server, sold the trailers, and bought them again, but it still doesn’t work on the server.

However, following your message, I just tested in SOLO mode with the same save, and it works perfectly!
Both logs and pallets, which were not working at all on the server, are functioning correctly.

Here are the screenshots!
![2300320_15](https://github.com/user-attachments/assets/a3b4a747-c5e7-4c00-8b2c-d5b758b714d4)
![2300320_14](https://github.com/user-attachments/assets/6625b0be-b80d-467a-8c92-4087064bc482)
![2300320_13](https://github.com/user-attachments/assets/c1a82121-ff84-446e-8ae0-9b5b7f97901e)
![2300320_11](https://github.com/user-attachments/assets/1cff1bb9-ba93-4a0e-aed4-a9f45524eab4)

**Comment by Keentin** [comment]
After checking, everything works perfectly, including the server!

VeryGames was undergoing updates following the FS25 update at 2 PM!
That must have caused issues on the server!

Thanks again!!

**Comment by loki79uk** [comment]
It could just be that it needed a restart.  I was going to suggest transferring your local settings file to the server and restart, but glad it is working now.  I still need to develop a robust way to transfer settings from client to server at the point of purchase (see #69)

**Comment by loki79uk** [comment]
So it sounds like I can close this one now as resolved.
