### ISSUE TITLE
Log loading stops early with "Unable to load more items of this size"

### ISSUE THREAD

**Issue by joscha999** [loki79uk/FS25_UniversalAutoload#116]
Trying to load some logs cut to 7.5m with a trailer configured to just above 7.6m but it stops early not using the whole available space.
I'm not sure if this is related to New Frontiers but it seems like New Frontiers forest version does throw a bunch of `2024-12-11 14:09 ZERO SIZE SPLITSHAPE 891058` on load.

Trying to load there's no error, just start and stop lines and the view as you can see in the attached screenshot - whole log is also attached.
```
2024-12-11 15:24 START Loading: Riedler Fahrzeugbau RUH327 - UAL #1196196 (5)
2024-12-11 15:24 STOP LOADING (items loaded = 5)
```

Let me know if you want the save to test this specific situation, just made a backup. While I have a bunch of mods loaded it should load fine without any mods (except New Frontiers obviously) as I'm not using any modded vehicles atm.

![image](https://github.com/user-attachments/assets/93cb4ea3-9d1d-4895-8a07-dbe6e77227f6)
[log.zip](https://github.com/user-attachments/files/18097301/log.zip) - Zipped as it's 5mb due to ZERO SIZE SPLITSHAPE logs

**Comment by loki79uk** [comment]
Do you know what objects have zero size?  Could you try moving the trailer away from the log pile and move the logs one at a time with super strength into the loading triggers until the message shows up.

**Comment by loki79uk** [comment]
Is it definitely set as a log trailer in your xml?  If you configured it before v0.2.0.0 and didn't delete those settings or remove the whole settings file then it won't be using the log loading, just loading logs as "normal" pallets.

**Comment by joscha999** [comment]
Just rebought the trailer after removing it from the config and yep, the `<options isLogTrailer="true"/>` was missing.
Checked the backup I made and it loaded the whole stack of logs (even loaded a little too much).

I'm not 100% sure if you want to add a migration or similar for this so I'll leave the issue open for now - feel free to close it otherwise tho :)

**Comment by loki79uk** [comment]
I'll close it for now, and I put a bigger message about removing old settings on the release notes this time
