### ISSUE TITLE
Warning: Missing l10n 'input_UNIVERSALAUTOLOAD_SHOP_CONFIG'

### ISSUE THREAD

**Issue by criss20ster** [loki79uk/FS25_UniversalAutoload#117]
I just downloaded the latest version and got something like this 

Warning: Missing l10n 'input_UNIVERSALAUTOLOAD_SHOP_CONFIG' in mod 'FS25_UniversalAutoload'

**Comment by loki79uk** [comment]
Don't worry about it at all, it is just a warning.  That string will be used for the shop menu when I've finished it, but not needed currently as there is no menu yet.

**Comment by criss20ster** [comment]
> Don't worry about it at all, it is just a warning. That string will be used for the shop menu when I've finished it, but not needed currently as there is no menu yet.

Ok but I think I fixed it. In the pl translation there was no entry

**Comment by loki79uk** [comment]
Yes, there is no entry in any language file yet.  When I have added all new >50 menu strings I will copy them to all languages.  You can never see this string at the meoment, so it doesn't matter if it is missing for now.

**Comment by loki79uk** [comment]
I have added a load of strings in the latest release, inlcuding this one.
https://github.com/loki79uk/FS25_UniversalAutoload/releases
