### ISSUE TITLE
Partially full BigBags do not activate the autoload trigger - V 0.2.0.1

### ISSUE THREAD

**Issue by maurojunior2011** [loki79uk/FS25_UniversalAutoload#118]
If I buy 10 BigBags (each with a thousand liters of seed) and partially use 4 of them (6 have a thousand liters of seed and the other 4 have 700 liters, for example), only the 6 with a thousand liters are loaded, the other 4 do not even trigger (the option to load them does not appear).

Example with 1 BigBag: (Sorry the game is in PT-BR).

A) I bought these 4 items:
![20241211224959_1](https://github.com/user-attachments/assets/6ea2b7c2-7db3-4724-aeca-8df975b00998)

B) When coupling the tractor, notice that the AutoLoad option appears
![20241211225030_1](https://github.com/user-attachments/assets/79153155-9b46-439d-a83d-eb5a591baf49)

C) After using 300L to fill the implement, there is 700L left inside the BigBag, now when coupling the tractor, the AUTOLOAD option does NOT appear
![20241211225113_1](https://github.com/user-attachments/assets/7183fa4b-cd8e-40c0-92d3-7432840788b8)

**Comment by loki79uk** [comment]
Press "O" to toggle the loading filter from full only to any.

**Comment by maurojunior2011** [comment]
Thank you, that was exactly it, I confess I didn't see the option.
