### ISSUE TITLE
UAL small issue

### ISSUE THREAD

**Issue by Sprinkadink** [loki79uk/FS25_UniversalAutoload#119]
So i might just be missing something but when I buy a new vehicle or trailer that is UAL compatible and want to edit the zones on them to be bigger or wider I can's seem to get the changes to save. I have gotten it to work for a few times on a few things but its been very hit or miss. Is there something that I am missing in the shop or some setting that I have missed? Thank you in advance and I love the mod so far keep up the good work.

**Comment by loki79uk** [comment]
It should save the last configuration every time you buy.  Can you look in the mod settings file to verify if the numbers change after buying?

**Comment by loki79uk** [comment]
Are you still having trouble with this?

**Comment by loki79uk** [comment]
Closing as can't reproduce / stale.  If this is still happening with the latest version and a new savegame then please re-open and attach a log file from the game where you reproduced the issue.
