### ISSUE TITLE
Error when exiting the game

### ISSUE THREAD

**Issue by Henkaix** [loki79uk/FS25_UniversalAutoload#12]
Hello loki First of all, thank you for providing us with this mod. I tested the mod and it works fine for now. But the game gives error if we don't sell the mod before quitting the game. I wanted to let you know about this error. I hope this problem will be solved in future releases.

**Comment by loki79uk** [comment]
There is no mod to sell, so I'm not sure what you mean.  Can you show me the error?

**Comment by loki79uk** [comment]
We spoke on Discord.  I think this was some kind of mod conflict, but can't reproduce.  Please re-open, or message me on Discord if it happens again.
