### ISSUE TITLE
Adjust box size area on Mac

### ISSUE THREAD

**Issue by pedrosantiagobarata** [loki79uk/FS25_UniversalAutoload#121]
Using version 0.2.0.0 on a Mac version of FS25.
It is not possible to configure the size of the "box" area inside a trailer, and the areas do not cover the full size of the trailer by default.
The little nodes to expand or retract the area are not available.
<img width="1920" alt="Screenshot 2024-12-12 at 12 03 46" src="https://github.com/user-attachments/assets/b17e3de4-eea8-417b-8415-75f1b053c804" />

**Comment by loki79uk** [comment]
Do you not have a middle click button on macs?  Have you tried apple key and click, or both left+right together, etc?

**Comment by pedrosantiagobarata** [comment]
I've tried almost every combination possible. Even with Command-click (right or left), that should the default behavior, but it seems that does not want to enter the "box" adjustment state.

**Comment by loki79uk** [comment]
I'll add a bindable key/action for this.  It may not even be needed eventually if I can make a setting in the menu to enable adjustment.  I have to actually make a menu first and see what is possible.

**Comment by pedrosantiagobarata** [comment]
That's fine. Having a setting to enable adjustment would be amazing. Thank you for looking into this.

**Comment by loki79uk** [comment]
Should be settable in the latest release.  Please try on mac and let me know.
https://github.com/loki79uk/FS25_UniversalAutoload/releases

**Comment by pedrosantiagobarata** [comment]
It now triggers the editing box size, I can see the dots, but on mac a new "issue" emerged. Since the RMB is used to rotate the object (trailer) I cannot adjust the size of the box. Although it recognises the hover state on the pink dot, each time I try to adjust the size, it just rotates the trailer. 

<img width="1920" alt="Screenshot 2024-12-13 at 11 00 35" src="https://github.com/user-attachments/assets/d4f2d817-0d1f-49e9-ba28-a3d52cd7779e" />

**Comment by loki79uk** [comment]
What is left click used for?  I thought left and right click would be guaranteed.  I could add a key binding, but it doesn't make much sense to be able to bind "click and drag" to keys though.

**Comment by pedrosantiagobarata** [comment]
Sorry, my bad. Above, where you RMB, it should be LMB.

- When I Press A -> Autoload Settings -> Ok on the modal window - nothing happens. The pink dots do not appear.
- So, I went to bind my RMB to be able to enter edit mode in the controls menu, and that was causing the conflict.
- I now bind a new key (E) to be able to enter edit mode, and RMB is correctly adjusting the size of the box.

Yes, it is working.

**Comment by pedrosantiagobarata** [comment]
Let me know if you need anything tested on a mac. Happy to help.
