### ISSUE TITLE
V0.2.0.1 - Not able to save loading area

### ISSUE THREAD

**Issue by JScoff** [loki79uk/FS25_UniversalAutoload#122]
Hi,

I have a problem saving the area change in shop / workshop.

Clicking middle button and adjusting blue box size
Then clicking middle button again, applying changes - and size is getting back to default.

Am I doing something wrong or is it a mod issue? 
I've deleted mod setting file before updating mod version

Thanks a lot in advance!

**Comment by loki79uk** [comment]
How are you "applying changes"?  you mean you bought a new vehicle?

**Comment by JScoff** [comment]
Either buying a new vehicle or editing existing one (which was bought after installing the mod and deleting configuration file).

**Comment by loki79uk** [comment]
Can you attach your log file please?  so I can see what is happening

**Comment by JScoff** [comment]
Sure. Where can I find it and should I enable dev mode / something else to log the actions?

**Comment by JScoff** [comment]
Please find attached

[log.txt](https://github.com/user-attachments/files/18118334/log.txt)

**Comment by loki79uk** [comment]
So which vehicle are you trying to change?  It says you bought a LODE KING Renown Drop Deck and sizes were saved as:
```
loadingArea(0)#width = 2.4628891944885254 
loadingArea(0)#length = 3.3256664276123047 
loadingArea(0)#height = 2.4901809692382812 
loadingArea(1)#width = 2.462953805923462 
loadingArea(1)#length = 11.449926853179932 
loadingArea(1)#height = 2.5495071411132812 
```

But before that it wasn't loading properly.  Can you send me your settings file too at, e.g.:
C:\Users\Loki\Documents\My Games\FarmingSimulator2025\modSettings\UniversalAutoload.xml

**Comment by JScoff** [comment]
XML settings are below, git is not allowing to attach it =(

Hm, seems the reason is that I'm trying to edit the size for a vehicle which was bought before installing mod - it works in general, but changing loading area is not being saved. Am I correct that if I want to change the size of loading area on some vehicle in workshop, I have to not only change the area size, but also make some another change - like change the license place?


<?xml version="1.0" encoding="utf-8" standalone="no"?>
<universalAutoload>
    <vehicleConfigurations>
        <vehicle configFileName="data/vehicles/stema/trius/trius.xml">
            <configuration selectedConfigs="1">
                <loadingArea offset="-0.000 0.780 -0.021" width="2.021282" length="4.016039" height="1.836044"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/lizard/multiPurposeTruck/multiPurposeTruck.xml">
            <configuration selectedConfigs="1">
                <loadingArea offset="0.000 0.958 -0.959" width="1.853855" length="3.582880" height="2.089353"/>
            </configuration>
            <configuration selectedConfigs="3">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="0.000 0.958 -0.960" width="2.005976" length="3.586085" height="2.143969"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="C:/Users/Johnny/Documents/My Games/FarmingSimulator2025/mods/FS25_FreightlinerM2stakebed/freightlinerM2.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="-0.004 1.353 -1.191" width="2.608947" length="7.966641" height="3.077682"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/lodeKing/renownTriAxleBeavertailLowDrop/renownTriAxleBeavertailLowDrop.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.012 1.568 6.242" width="2.462889" length="3.325666" height="2.490181"/>
                <loadingArea offset="0.012 0.883 -1.149" width="2.462954" length="11.449926" height="2.549507"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/international/cvSeries/cvSeries.xml">
            <configuration selectedConfigs="2|1" useConfigName="enterablePassenger">
                <loadingArea offset="0.000 1.054 -1.749" width="5.893403" length="3.878104" height="4.259316"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/kroeger/pwo24/pwo24.xml">
            <configuration selectedConfigs="1">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="-0.033 1.276 -0.176" width="10.234457" length="9.775215" height="4.832708"/>
            </configuration>
        </vehicle>
    </vehicleConfigurations>
</universalAutoload>

**Comment by JScoff** [comment]
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<universalAutoload>
    <vehicleConfigurations>
        <vehicle configFileName="data/vehicles/stema/trius/trius.xml">
            <configuration selectedConfigs="1">
                <loadingArea offset="-0.000 0.780 -0.021" width="2.021282" length="4.016039" height="1.836044"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/lizard/multiPurposeTruck/multiPurposeTruck.xml">
            <configuration selectedConfigs="1">
                <loadingArea offset="0.000 0.958 -0.959" width="1.853855" length="3.582880" height="2.089353"/>
            </configuration>
            <configuration selectedConfigs="3">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="0.000 0.958 -0.960" width="2.005976" length="3.586085" height="2.143969"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="C:/Users/Johnny/Documents/My Games/FarmingSimulator2025/mods/FS25_FreightlinerM2stakebed/freightlinerM2.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="-0.004 1.353 -1.191" width="2.608947" length="7.966641" height="3.077682"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/lodeKing/renownTriAxleBeavertailLowDrop/renownTriAxleBeavertailLowDrop.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.012 1.568 6.242" width="2.462889" length="3.325666" height="2.490181"/>
                <loadingArea offset="0.012 0.883 -1.149" width="2.462954" length="11.449926" height="2.549507"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/international/cvSeries/cvSeries.xml">
            <configuration selectedConfigs="2|1" useConfigName="enterablePassenger">
                <loadingArea offset="0.000 1.054 -1.749" width="5.893403" length="3.878104" height="4.259316"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/kroeger/pwo24/pwo24.xml">
            <configuration selectedConfigs="1">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="-0.033 1.276 -0.176" width="10.234457" length="9.775215" height="4.832708"/>
            </configuration>
        </vehicle>
    </vehicleConfigurations>
</universalAutoload>

```

**Comment by loki79uk** [comment]
Those all look sensible, the settings from the lodeking are as above:
```xml
        <vehicle configFileName="data/vehicles/lodeKing/renownTriAxleBeavertailLowDrop/renownTriAxleBeavertailLowDrop.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.012 1.568 6.242" width="2.462889" length="3.325666" height="2.490181"/>
                <loadingArea offset="0.012 0.883 -1.149" width="2.462954" length="11.449926" height="2.549507"/>
            </configuration>
        </vehicle>
```

Yes, to save in the workshop you have to make some other change (number plate, etc) FIRST, and then set the size and then buy it.  If you change anything after adjusting the UAL settings, then they will be reset because the game creates a new vehicle every time you change a configuration option.

**Comment by loki79uk** [comment]
I need to remove the mod folder from the full path written to the xml so the file can be transfered to other machines.

**Comment by JScoff** [comment]
Gotcha =)

So I guess I will just sell all autoload vehicles I have, save the game, then delete mod settings - and then configure and buy it one more time

**Comment by loki79uk** [comment]
You can also just buy them in a totally different savegame and then reload that one

**Comment by loki79uk** [comment]
> I need to remove the mod folder from the full path written to the xml so the file can be transfered to other machines.

I've done this now: https://github.com/loki79uk/FS25_UniversalAutoload/issues/124

**Comment by loki79uk** [comment]
Is it all working for you now?

**Comment by JScoff** [comment]
Sorry for the late reply, it's working now =)
