### ISSUE TITLE
Remove mod directory from paths in settings xml

### ISSUE THREAD

**Issue by loki79uk** [loki79uk/FS25_UniversalAutoload#124]
All versions up to now used the full xml path to identify a vehicle in the mod settings xml, e.g.:

![image](https://github.com/user-attachments/assets/e530b433-a466-4771-82eb-6303a101867b)

I didn't even think about mods having different paths until I started seeing them, and this not only makes the strings unnecessarily long but also makes transfer of files between different machines more difficult.  There was a line to remove the mod dir for the comparision before, but not the DLC folder.

I will add a new feature to the next release (v0.2.1.1) to silently clean the paths the next time settings are saved for a vehicle, e.g.:

![image](https://github.com/user-attachments/assets/d3e3b55b-f34a-4d3e-9c1b-5e75fd94eecd)

There shouldn't be any issues (and I have tested this one) but I could easily have missed something, so if you get any errors please open a new bug or reply here.

**Comment by aurelien2023** [comment]
It seems like not clearing the full xml path.
as I play on a notebook and on a desktop, i don't have the same path for the mods, so I have 2 entries in UAL.xml

UAL v0.2.1.4


 ```
<vehicle configFileName="C:/Users/aurel/OneDrive/FS25/FS25_PongeSPX/spx816.xml">
            <configuration selectedConfigs="ALL">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="0.008 1.387 1.337" width="3.100000" length="8.700000" height="3.900000"/>
            </configuration>
        </vehicle>
```
        <vehicle configFileName="C:/OneDrive/FS25/FS25_PongeSPX/spx816.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.008 1.387 1.302" width="3.100000" length="8.700000" height="3.900000"/>
            </configuration>
        </vehicle>
```

**Comment by loki79uk** [comment]
Okay, I didn't know that was possible - so you have two mod paths set?

**Comment by aurelien2023** [comment]
it's not working, 

1. i've delete the UAL config file :
in the new one : 
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<universalAutoload>
    <vehicleConfigurations>
        <vehicle configFileName="C:/OneDrive/FS25/FS25_PongeSPX/spx816.xml">
            <configuration selectedConfigs="ALL">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="0.008 1.387 1.337" width="2.296025" length="8.022907" height="2.305054"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/farmtech/dpw1800/dpw1800.xml">
            <configuration selectedConfigs="ALL">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="0.000 1.130 -0.832" width="3.365257" length="9.579478" height="3.135054"/>
            </configuration>
        </vehicle>
    </vehicleConfigurations>
</universalAutoload>

```

2. Then I delete the path and go for editing my config, then : It didn't recognize the entries and create a new one : 

the Load area missing : 
![Farming Simulator 25 Screenshot 2024 12 16 - 09 03 02 30](https://github.com/user-attachments/assets/7d8fe9fd-7379-4102-950f-13eda787cb6b)

editing create a new entrie:
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<universalAutoload>
    <vehicleConfigurations>
        <vehicle configFileName="FS25_PongeSPX/spx816.xml">
            <configuration selectedConfigs="ALL">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="0.008 1.387 1.337" width="2.296025" length="8.022907" height="2.305054"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/farmtech/dpw1800/dpw1800.xml">
            <configuration selectedConfigs="ALL">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="0.000 1.130 -0.832" width="3.365257" length="9.579478" height="3.431478"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="C:/OneDrive/FS25/FS25_PongeSPX/spx816.xml">
            <configuration selectedConfigs="ALL">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="0.008 1.387 1.337" width="2.296024" length="8.022907" height="2.305046"/>
            </configuration>
        </vehicle>
    </vehicleConfigurations>
</universalAutoload>


```

**Comment by loki79uk** [comment]
Are both of your games using the same version?  I don't really understand what is going on - you have the game installed on two devices, but are using OneDrive to sync the mods folder, but using a different path?

**Comment by aurelien2023** [comment]
yes it's exactly that i've not set the same path for OneDrive on my 2 devices.

It's not a big deal with copy/paste i can do 2 differents config for each mods, but you were saying the entire path will not get any longer ssave in the config.xml, but it's not or not anymore, there is still the total path.
for me it's not a problem as i have not a lot of entries duplicate today and I have no problems editing xml.
But I think you could have some people asking for config not being save if they use differents mod folders for differents save/mods (as people using mods managers like : [FSG Mod Assistant](https://fsgmodding.github.io/FSG_Mod_Assistant/))

**Comment by loki79uk** [comment]
It is supposed to strip the mods path now.  I don't understand how it can be written like that if you are using the latest version on both.  Maybe Steam is restoring an old file?

**Comment by aurelien2023** [comment]
I don't think it's steam, 
When I delete the xml it was recreate by the game as soon as I configure a new trailer in the shop, with only the new line.
then I exit the game, edit the path, and there " Load area missing"
I believe it's broken... at least on the last release, i didn't try before.
I'll try the 0.2.0.1 and let you know.

**Comment by aurelien2023** [comment]
not working for v0.2.1.1 neither... maybe it's broken because I'm using the base game mods path :
Documents\My Games\FarmingSimulator2025\mods
Will try a new save wtih the original mods path

**Comment by aurelien2023** [comment]
If you use the base game mods path :
Documents\My Games\FarmingSimulator2025\mods
**It works perfectly**

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<universalAutoload>
    <vehicleConfigurations>
        <vehicle configFileName="data/vehicles/farmtech/dpw1800/dpw1800.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.000 1.130 -0.832" width="3.100000" length="9.50" height="3.900000"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="FS25_PongeSPX/spx816.xml">
            <configuration selectedConfigs="ALL">
                <options isBaleTrailer="true" horizontalLoading="true"/>
                <loadingArea offset="0.008 1.379 1.297" width="2.907333" length="9.198504" height="3.737059"/>
            </configuration>
        </vehicle>
    </vehicleConfigurations>
</universalAutoload>
```

**Comment by loki79uk** [comment]
Are you just setting the mod path in the game xml?  I use a custom path (different drive) and works for me, so I'm not sure what can be going on here?

**Comment by aurelien2023** [comment]
yes 
```
<gameSettings revision="15">
    <modsDirectoryOverride active="true" directory="C:\OneDrive - ABCD\FS25"/>
```

**Comment by aurelien2023** [comment]
### Found it
it was special characters in the path folder (space) :

**NOT working** :
```
E:/OneDrive - ABCD:FS25/mods
C:/OneDrive - ABCD/FS25
C:/Users/aurel/OneDrive - ABCD/FS25

```

**Working** :
```
E:/mods
E:/FarmingSimulator2025/mods
```
