### ISSUE TITLE
holztransporte

### ISSUE THREAD

**Issue by OpiGunnar** [loki79uk/FS25_UniversalAutoload#126]
![image](https://github.com/user-attachments/assets/d382ce79-3b51-4eee-abee-bb81b39755d1)
mehr geht da nicht,ernsthaft???

**Comment by loki79uk** [comment]
Did you resize the box before purchase?  see: https://github.com/loki79uk/FS25_UniversalAutoload/issues/125

Otherwise, if you did and are on multiplayer, then see: https://github.com/loki79uk/FS25_UniversalAutoload/issues/69

**Comment by OpiGunnar** [comment]
grösse geändert? ich schau nach

**Comment by loki79uk** [comment]
Please post a screenshot with visual debug mode on (shift-crtl-F12)

**Comment by OpiGunnar** [comment]
![image](https://github.com/user-attachments/assets/2e177294-b853-4b49-84b4-bad203f6e6a2)
man(n) lernt nie aus,die pfeile zeigen auf die änderungspunkte zum einstellen. hat bissel gedauert um es zu sehen,aber ja mit brille .... ;-)

**Comment by OpiGunnar** [comment]
ok,entschuldigung wenn das vieleicht bissel grob rüber kam,war nicht so gemeint

**Comment by OpiGunnar** [comment]
![image](https://github.com/user-attachments/assets/dcc0f975-b9a2-486a-9047-36487c83ae33)

was mach ich falsch? die einstellungen werden nicht übernommen!

**Comment by loki79uk** [comment]
That is much too high, you need the blue box to fill the whole area where you want logs to be, otherwise you will not be able to unload them.

To apply changes it is easier to buy a new one.  If you want to change in the workshop, then change the wheels or number plate FIRST to make the configuration button active.  It also looks like you are on an old version since there is no shop menu.  Please update to the latest.

**Comment by OpiGunnar** [comment]
eigentlich nicht,hatte heute morgen erst geupdatet.
mache mal einen kompletten neustart und check mal updates für den server und client

**Comment by OpiGunnar** [comment]
[log.txt](https://github.com/user-attachments/files/18126764/log.txt)

**Comment by loki79uk** [comment]
> [log.txt](https://github.com/user-attachments/files/18126764/log.txt)

you are still on `v0.2.0.0`

**Comment by OpiGunnar** [comment]
![image](https://github.com/user-attachments/assets/9d6e2d9a-a5d8-4421-8e2a-8a18d94d1929)
nu mal schauen

**Comment by loki79uk** [comment]
well, where did you get it from, because the log file you sent me says:
![image](https://github.com/user-attachments/assets/b71108e6-d025-4880-b3e3-08e3ba8e7345)

**Comment by OpiGunnar** [comment]
jap,hab es erneuert (updatet)

**Comment by OpiGunnar** [comment]
![image](https://github.com/user-attachments/assets/ed5fbf33-f83b-40b7-963a-72d3d28f9b36)

?
