### ISSUE TITLE
WARNING: load area missing - check settings file

### ISSUE THREAD

**Issue by KerlvomSee** [loki79uk/FS25_UniversalAutoload#127]
Hello,

no matter how often I change and save the loading zone in the shop, there is never anything in A Autoload and after save, closing and reloading the Game, i have to do all the configurations again because it writes in the log for all vehicles with Autoload:

2024-12-13 14:24 INTERNATIONAL Series 200: UAL - tension belts (5)
2024-12-13 14:24 UniversalAutoload - supported vehicle: INTERNATIONAL Series 200 #1 (Design 1)
2024-12-13 14:24 *** NO MATCHING LOCAL CONFIG - #1 (Design 1) ***
2024-12-13 14:24 CREATE REAL VEHICLE: INTERNATIONAL Series 200
2024-12-13 14:24 INTERNATIONAL Series 200: UAL SETTINGS WERE NOT ADDED
2024-12-13 14:24 INITIALISE UAL VEHICLE (ON LOAD) 497437
2024-12-13 14:24 WARNING: load area missing - check settings file
2024-12-13 14:24 UAL: ON POST LOAD
2024-12-13 14:24 using xml key - vehicles.vehicle(261).FS25_UniversalAutoload.universalAutoload.currentState
2024-12-13 14:24 UAL: ON POST LOAD COMPLETE

This is what the Universal Autoload.xml looks like:

![2024_12_13_14_38_42_](https://github.com/user-attachments/assets/797a0b2d-2adf-46f0-891b-3dd548f4fba1)

![2024-12-13 14_34_20-Farming Simulator 25](https://github.com/user-attachments/assets/69e5130a-b438-4abe-be25-a5788729eff7)

Although the Universal Autoload.xml is present, its content is never loaded. However, changes are saved as soon as I make changes to the trigger in the shop. 

I use: <version>0.2.1.1</version>

My gameSettings.xml for modsDirectory:

![grafik](https://github.com/user-attachments/assets/c7cf048e-2f65-456a-ae4b-81fb01b81abc)

My directory for data is here: D:\daten\Documents\My Games\FarmingSimulator2025\modSettings

**Comment by loki79uk** [comment]
I think this is an incorrect value for selectedConfigs written by an earlier version.  Can you try removing the whole entry for that vehicle and buying again, or just edit it to look like this:

![image](https://github.com/user-attachments/assets/b5d3782c-7556-49f7-88f2-da562c46422a)

**Comment by KerlvomSee** [comment]
I deleted the file and recreated all entries. Now it at least loads the configurations again.

Changing the configuration between versions is really bad. There is also only one configuration for different trailer lengths, why? This was solved better before. This is the one configuration that is now loaded for all trailer sizes. Not good!

![2024-12-13 15_39_42-Farming Simulator 25](https://github.com/user-attachments/assets/62f3dd44-7605-468f-94b4-91261cad0f85)
![2024-12-13 15_40_37-Farming Simulator 25](https://github.com/user-attachments/assets/565a79f1-c2f2-42da-9c63-514900c065b1)

Why not like this anymore?
![2024-12-13 15_47_08-D__UniversalAutoload xml - Notepad++](https://github.com/user-attachments/assets/85b16661-a297-4626-adfb-363aef7b8560)

**Comment by loki79uk** [comment]
The problem is all of the other trailers with "design" as a variable where all it does is change the lights or a wingmirror or something.  There were a lot of vehicles NOT picking up configs because the deign was different.  I'll have to decide how to handle these special cases.

**Comment by loki79uk** [comment]
For now I can add a special case for this trailer, but it is not a good solution in the long term.

**Comment by KerlvomSee** [comment]
OK. I understand what you mean. But I have no idea how you could solve this cleverly for all trailers.

**Comment by loki79uk** [comment]
If modders acutally used proper configuration SETS, then it wouldn't be an issue.  But how do we know what they called the one configuration that changes the length, it could be "design" or it could be anything "cab_design", "length", "feature1", etc..

The best I can come up with is it will be an option in the menu (when I make it) as it clearly needs user input and could never be guesed programatically (why GIANTS made configuration sets, but no modders use them)

**Comment by KerlvomSee** [comment]
> For now I can add a special case for this trailer, but it is not a good solution in the long term.

You don't have to do that because of me. I can adjust the trigger.

**Comment by KerlvomSee** [comment]
> If modders acutally used proper configuration SETS, then it wouldn't be an issue. But how do we know what they called the one configuration that changes the length, it could be "design" or it could be anything "cab_design", "length", "feature1", etc..
> 
> The best I can come up with is it will be an option in the menu (when I make it) as it clearly needs user input and could never be guesed programatically (why GIANTS made configuration sets, but no modders use them)

It's best to write about it somewhere in the moddesc or in the changes. Then it shouldn't be a problem to change the trigger.

The nomenclature doesn't change anymore and the UniversalAutoload.xml doesn't have to be changed again?

**Comment by loki79uk** [comment]
sorry I tried to reply and it went wrong

or edit your xml like this:
<configuration selectedConfigs="ALL|1" useConfigName="design">

**Comment by loki79uk** [comment]
I t is literally just me working on this and I have been changing so much stuff in the last 2 weeks I just missed that change would affect random mods - I'm only using base game vehicles for now.  Anything else, inlcuding MP is just a bonus if it works.

**Comment by loki79uk** [comment]
> It's best to write about it somewhere in the moddesc or in the changes. Then it shouldn't be a problem to change the trigger.

Changing the trigger is not acceptable for me, there will be something like a dropdown in the menu where you choose the feature that you want to use as the configuration identifier

**Comment by KerlvomSee** [comment]
No problem. I haven't changed anything in terms of the trailer's configuration compared to the original. It does load wood. 

When making changes, I recommend deleting the Universal Autoload.xml in the current version and re-creating all entries. Then it will work, I think!

![grafik](https://github.com/user-attachments/assets/b0d0fcb8-0791-45cc-8431-93b58ac54c73)

For me it's cleared up and my problems solved.

Thank you for your quick help. GREAT!!!

**Comment by KerlvomSee** [comment]
If that is the best solution for you, then the file needs to be recreated. That's what I did. If you're smart, you save the old file, recreate it and copy the values ​​from the old one into the new one. If you're not, you'll have to recreate everything. 

You can't please everyone.

I'm glad that you're so fast and that your scripts are already running so well. Thanks for that!

**Comment by loki79uk** [comment]
That does make sense if you know what is going on, but I think a large percentage of users have no idea that the mod settings file even exits, and even less idea how to edit it.

In the final release, there will be a default XML with all the base game stuff already configured, but for now it is just whatever the algorithm detects.  It will always be an issue for people who configured their stuff with an older version.

**Comment by KerlvomSee** [comment]
That's true. And I'm sure you'll get it resolved as best as possible.

Thanks for your great work.

Can you close the entry or should I?

**Comment by loki79uk** [comment]
I made a change related to this in the last release: https://github.com/loki79uk/FS25_UniversalAutoload/issues/140#issuecomment-2547865439
