### ISSUE TITLE
Seeing double letters in menu when using UAL

### ISSUE THREAD

**Issue by grantdv** [loki79uk/FS25_UniversalAutoload#128]
Hey All,
I started using UAL version 09 worked great in Single Player (SP), a little buggy, but otherwise awesome.
I started playing Multi-Player (MP), and my problems began there. I know it's not supported in MP, so if it worked at all I was happy. After a week or so, I upgraded to 18, and I got the double letters in the menu, but it no longer worked.
I upgraded to the latest version last night on a fresh SP game, no joy. I completely wiped FS25 off my computer and reinstalled a fresh SP game, no joy..
I don't know what else to do to fix this other than erasing the mod settings XML file for UAL I don't know what else to try, so I took a screenshot of the menu; maybe someone can tell me what to do to get it working again.

Thank you,
-Grant
![CleanShot 2024-12-12 at 19 08 59](https://github.com/user-attachments/assets/ae9509d3-4760-4c84-bf37-56ddf792765b)

**Comment by loki79uk** [comment]
I have never seen that before, I would definitely start by removing all UAL entries in your key bindings xml and restart the game.

**Comment by grantdv** [comment]
Dude, you’re awesome. that totally fixed it. There were 2 or 3 entries for UAL items in the bindings XML. I got rid of them, and it worked perfect.
