### ISSUE TITLE
V2.1.2 got rid of bales

### ISSUE THREAD

**Issue by ComplicatedBreakfast** [loki79uk/FS25_UniversalAutoload#130]
Bales worked in last version but nothing loaded correctly. Pallets load just fine now but bales no longer load onto trailer, not even option to load them. Other people on server the same issue.

**Comment by celendis** [comment]
I also experienced this issue with a locally-hosted multiplayer game. When attempting to load small bales onto the Farmtech EDK 650, I received a popup that no compatible goods were available. However, I also saw numerous errors in the log:
2024-12-14 01:16 Error: Running LUA method 'ualLoadingTrigger_Callback'.
C:/Users/Rich/Documents/My Games/FarmingSimulator2025/mods/FS25_UniversalAutoload/UniversalAutoload.lua:5160: attempt to compare number < nil
I have attached the full log to this comment.
[log.txt](https://github.com/user-attachments/files/18134611/log.txt)

**Comment by loki79uk** [comment]
Sorry about that, will fix today and add the bale console command too.

**Comment by loki79uk** [comment]
Should be fixed now.  I hope to add the bale and log console commands later today.

**Comment by loki79uk** [comment]
Have not made any progress on the console commands - but mainly because I got distracted with an actual working menu!

![image](https://github.com/user-attachments/assets/b8a4cf89-b391-4819-afc4-f6415c211017)

**Comment by ComplicatedBreakfast** [comment]
Looks good!

**Comment by loki79uk** [comment]
Do you prefer as above or uisng the game style?

![image](https://github.com/user-attachments/assets/913ce262-4436-47eb-ba5c-9245cc152e04)
