### ISSUE TITLE
Got a "buy me a coffee" link?

### ISSUE THREAD

**Issue by ComplicatedBreakfast** [loki79uk/FS25_UniversalAutoload#131]
Me and my friends would like to say thank you for the fast fix by buying you a quality coffee (not the cheap shit) on us.

**Comment by loki79uk** [comment]
Hi, thank you for the kind offer.  I don't have anything set up and am unlikely to get around to it. I'm glad that people appreciate all the effort, but honestly I would be doing it anyway.

I'll be at LAMMA in January, so if you have any plans to go I'm sure they will have coffee there, although I don't expect it will be good..

_duplicate of https://github.com/loki79uk/FS25_UniversalAutoload/issues/16_
