### ISSUE TITLE
bomen auto laden 

### ISSUE THREAD

**Issue by boedsr70** [loki79uk/FS25_UniversalAutoload#132]
ik kan geen bomen laden met auto load ja 2 of 3 stammen en dat is het kan dit worden opgelost

**Comment by loki79uk** [comment]
Did you resize the loading volume in the shop? Most of the log trailers are too small. See e.g.: https://github.com/loki79uk/FS25_UniversalAutoload/issues/125

**Comment by loki79uk** [comment]
> Maybe the same problem i have. I get this error message. i resized the loading volume in shop and there is some space left, as you can see.
Try making the loading volume taller - it does not even reach the top of the bars.  You can make it taller than the top of the trailer too if you want to.

**Comment by loki79uk** [comment]
Does this vehicle have the log trailer tag in your xml?

**Comment by loki79uk** [comment]
Okay, that is the issue - add it manually or try deleting the config and rebuying it.

I'm working on a menu right now which will make all this stuff possible from in the game.
