### ISSUE TITLE
material selection option not visible in top left menu

### ISSUE THREAD

**Issue by justasti** [loki79uk/FS25_UniversalAutoload#134]
hey!
first of all - amazing work and issue solving on the mod, keep on the good work!
about the issue - I'm not even sure is this mod issue or game, but in the top left menu, where the available controls are displayed, I see no option to change what materials to load/unload. I can cycle between them, but what I land on is complete guess. Maybe that's the game limiting amount of keybinds to show at once.
I'm playing on dedicated server if it's relevant. 
Sorry no screenshot, I'm not ingame now, but I can provide what's necessary to get better understanding of the issue, so if you need something, please let me know.
Thanks!

**Comment by loki79uk** [comment]
Check the log, but I think you need to choose a new key for chat or rebind that one.

**Comment by justasti** [comment]
Yep, remapping thw button solved it. Thanks!
