### ISSUE TITLE
LettusBoxPallet

### ISSUE THREAD

**Issue by hamilton-norm** [loki79uk/FS25_UniversalAutoload#136]
![15008282067899252736_10](https://github.com/user-attachments/assets/2daabdd6-bdb8-4e93-a61c-684e649d9639)

**Comment by loki79uk** [comment]
Don't worry about it, that is a message that I forgot to remove about a different object.  Lettuce boxes will still work fine.

**Comment by loki79uk** [comment]
Remove this degugging line.  Closing as fixed.
