### ISSUE TITLE
Autoload logs

### ISSUE THREAD

**Issue by BlueJay949** [loki79uk/FS25_UniversalAutoload#137]
I can't get the Pitts Logging trailer to load 12 meter logs. I tried several configuation but no luck.

Jay

**Comment by loki79uk** [comment]
You need to resize the box in the shop to be over 12m long.  I will add some feedback so you know the length, but for now if you turn on the debugging when loading it should tell you what the problem is.

**Comment by Napoleon231187** [comment]
So the box have to be the same sizes as the logs or it wouldn’t work ?

does it also count for the contract logs ?

**Comment by loki79uk** [comment]
Yes, the box has to be bigger than whatever items you want to load.  You can check the size in the mod settings xml for now, but I will add some kind of GUI feedback too.  And yes, it should load any splitshapes regardless of mission or manually cut trees, but let me know if there are any issues.

**Comment by Napoleon231187** [comment]
Well I tested it and it is working :-) just one problem the vanilla trailers aren’t mission friendly 🤣🤣🤣The big trailer has a huge gab in the middle where they fall out and the yellow lorry is to small But it is working Sent from my iPhoneOn 16 Dec 2024, at 19:41, Loki_79 ***@***.***> wrote:﻿
Yes, the box has to be bigger than whatever items you want to load.  You can check the size in the mod settings xml for now, but I will add some kind of GUI feedback too.  And yes, it should load any splitshapes regardless of mission or manually cut trees, but let me know if there are any issues.
