### ISSUE TITLE
Krone Profi Liner ->Strawberry

### ISSUE THREAD

**Issue by tempelon** [loki79uk/FS25_UniversalAutoload#139]
We got massive lags on our server when someone has loaded strawberry pallets on his "Krone Profi Liner". All other gods are fine.

**Comment by loki79uk** [comment]
Maybe they are clipping part of the frame - try making the loading volume box a tiny bit smaller, or raising it up slightly.

**Comment by loki79uk** [comment]
Closing as stale - please update to the latest version and feel free to re-open this bug if you are able to reproduce the issue
