### ISSUE TITLE
Mod is showing  in only one Menu 

### ISSUE THREAD

**Issue by 4nniiee** [loki79uk/FS25_UniversalAutoload#14]
Heya!
First of all thanks for the work and early release, really glad u stepped up for this!

The troubble im having is that i downloaded everything correctly and it does show up in my main Menu mod Folder, but when i want to start or load a Game it wont show again as option  and is not working in Game. 
Any clue what i may did wrong?

**Comment by 4nniiee** [comment]
In germany we say. the problem mostly sits in front of the PC. 

Fixed it.

**Comment by Stairs266** [comment]
What did you do to fix this? I'm having the same issue and cant figure out what I am doing wrong.
