### ISSUE TITLE
after reopening save autolaod stop working

### ISSUE THREAD

**Issue by ArneM16** [loki79uk/FS25_UniversalAutoload#140]
with the 2.1.4 update wen you reopen your save the autoload doesnt work anymore so you need to reconfire the zone again
![2300320_20241215184007_1](https://github.com/user-attachments/assets/187afd2f-57a8-4e72-be10-be224fff30eb)

**Comment by loki79uk** [comment]
Which version did you update from?  Can you attach your log from that game (when it happened) by any chance?

**Comment by ArneM16** [comment]
i came from either 0015 or the 0016

**Comment by loki79uk** [comment]
I think this is probably the same issue as https://github.com/loki79uk/FS25_UniversalAutoload/issues/127  If it happens again please let me know.

**Comment by ArneM16** [comment]
and how can i fix this issue short term so it doenst happen anymore?

**Comment by loki79uk** [comment]
Can you send me your mod settings file before I give you wrong advice, but it should work to remove that vehicle from your mod settings file and buy it again (can be in a different save).

**Comment by ArneM16** [comment]
[UniversalAutoload.zip](https://github.com/user-attachments/files/18141812/UniversalAutoload.zip)

**Comment by ArneM16** [comment]
can i maybe use the settings from the version i was using?

**Comment by loki79uk** [comment]
Yes, it is what I thought - so you can jsut remove all the parts with a pipe symbol.

e.g.:
```xml
        <vehicle configFileName="data/vehicles/demco/steelDropDeck/steelDropDeck.xml">
            <configuration selectedConfigs="ALL|1">
                <loadingArea offset="0.020 1.354 0.510" width="1.190825" length="9.438637" height="1.266563"/>
                <loadingArea offset="-0.000 1.010 -0.300" width="2.471684" length="11.252049" height="2.474899"/>
            </configuration>
        </vehicle>
```

should be changed to:
```xml
        <vehicle configFileName="data/vehicles/demco/steelDropDeck/steelDropDeck.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.020 1.354 0.510" width="1.190825" length="9.438637" height="1.266563"/>
                <loadingArea offset="-0.000 1.010 -0.300" width="2.471684" length="11.252049" height="2.474899"/>
            </configuration>
        </vehicle>
```

It was a failed idea to use the default "design" configuration, but the unexpected side effect was to make a load of extra items like this.  I should be able to add a script in to the startup to clean these, but for now you can just do it manually.

Please leave this bug open to remind me!

**Comment by loki79uk** [comment]
So not a complete solution, but what I'm doing now is to:
1) use the ammended string (e.g. "ALL|1" -> "ALL" )
2) change is not written to the file because it it likely to leave duplicates
3) added some lines in the log now to highlight these entries, e.g.:
```
ADDING SHOP ITEM data/vehicles/lizard/pickup2017/pickup2017.xml
*** SUGGEST REPAIRING CONFIG: ALL|1 - using ALL ***
```

**Comment by loki79uk** [comment]
Closing as mostly complete now.

I can't resolve completely without either:
1) Remove all previous settings (upsets people who will lose their settings)
2) Rename all settings (doesn't work because then there can be duplicates)
