### ISSUE TITLE
Not getting load option for Logs

### ISSUE THREAD

**Issue by ashoktmgl** [loki79uk/FS25_UniversalAutoload#141]
![autoload debug](https://github.com/user-attachments/assets/6523cb0a-3a35-4d8f-9f13-2706f078686c)
I am not getting load (left shift + R) to load logs for truck international CV series. I am using latest release 0.2.1.4. Please check attached debug image.

**Comment by loki79uk** [comment]
The loading area looks like it is not long enough for those logs.  Try cutting them smaller.  You can extend the loading area out the back if you really want to only use it for logs.

**Comment by ashoktmgl** [comment]
Yes, After extending back loading area it is worked. Thanks.
