### ISSUE TITLE
Bale collect mode not working with International CV series

### ISSUE THREAD

**Issue by Swampratt80** [loki79uk/FS25_UniversalAutoload#142]
Does not give me the option for bale collect mode when using the International CV series. Everything is working perfect except for that. Is there something I'm missing or something I need to edit in the xml for it? I assume it has something to do with isBaleTrailer=true but I'm not sure where to put that in the xml if that is the case. Any help would be greatly appreciated.

**Comment by loki79uk** [comment]
Yes you need that option.  Buy a bale trailer and copy the options to the truck.  Or wait a few more days because I'm making an in game menu too set the options.

**Comment by loki79uk** [comment]
Can you try setting as "bale trailer" with the new menu before purchase?

**Comment by Swampratt80** [comment]
Yes, it works perfect now with the new update. Thank you very much.
