### ISSUE TITLE
Log trailer mod question

### ISSUE THREAD

**Issue by dirkchamp78** [loki79uk/FS25_UniversalAutoload#144]
Hello, my Manac log trailer mod works but in store I have 2 boxs to resize. I have to resize them both to the same dimensions in order for it to work. Works fine once I do that but wondering if there's something in the mod I need to change or if you have run into this? Mod is error free and pretty much setup like the in game trailer. 

Thanks

**Comment by loki79uk** [comment]
That will only happen if all of the tension belts are not on the same plane - the algorithm assumes that if the tension belts are in different planes then it is a multi platform vehicle e.g. a low loader.  You can safely set one very small for now, or manually remove it in your mod settings file.  I will add some menu options or special key combinations to add or remove these zones from in game.

**Comment by geeknessfr** [comment]
Hi, can we found this trailer somewhere so we can debug it, now and later ? I searched for it, but couldn't fine it...

**Comment by dirkchamp78** [comment]
It's not public yet but I can release it after work on my itch page https://expendabledirk.itch.io/. Check my itch page around 6 p.m. EST or if you're on my Facebook page message me (Derek Champlin) and I'll share a link. https://www.facebook.com/groups/ExpendablesModding

**Comment by geeknessfr** [comment]
Oh, ok, thanks a lot, I didn't understand you did this trailer, sorry !

I'm not on facebook, but I'll wait for the release, no problem.

**Comment by geeknessfr** [comment]
Ok I downloaded the trailer, thanks @dirkchamp78.

I put some other screenshots : (Default state for UAL Loading Zones)

![image](https://github.com/user-attachments/assets/5792673f-94d8-4075-b8f3-4011f0d272e8)

![image](https://github.com/user-attachments/assets/bc77672d-edc7-4fee-b72b-e98b805caabe)

**Comment by dirkchamp78** [comment]
Awesome, I'm so use to making custom vehicle types even though I didn't need to for this trailer I did anyway. Thanks for the feedback @geeknessfr.

**Comment by loki79uk** [comment]
Closing as expected behaviour.  Mod is supposed to detect two levels and make two zones.  I will eventually add some mechanism in the menu to add and remove new zones, but that was already a planned feature, I don't need this bug open to remind me.
