### ISSUE TITLE
Bug: Selling equipment then locks you from buying new equipment

### ISSUE THREAD

**Issue by cblain22** [loki79uk/FS25_UniversalAutoload#146]
If you sell equipment, then attempt to buy anything else, you can get to the categories page but cannot select any specific equipment to then buy.

Steps to reproduce bug:

1. Sell any equipment
2. Open Store
3. Select any category
4. Try and fail to select any equipment

**Comment by cblain22** [comment]
Reloading the save allows you to buy again, but selling anything after that resets the issue

**Comment by loki79uk** [comment]
I can't reproduce this - sold everything I owned, and then bought this trailer:

![image](https://github.com/user-attachments/assets/26b8b433-39ca-45fb-8730-fa6d58ae61bc)

Please do attach a log file, that would help a lot!

**Comment by cblain22** [comment]
[log.txt](https://github.com/user-attachments/files/18162931/log.txt)

**Comment by loki79uk** [comment]
Can you try removing all old versions, download from GitHub and start a new savegame?
https://github.com/loki79uk/FS25_UniversalAutoload/releases/latest/download/FS25_UniversalAutoload.zip

**Comment by cblain22** [comment]
Okay cool!
Not sure why it worked as I just installed the -seemingly- same zip file from the above website and started having issues today. But I deleted the mod and the mod settings and downloaded your commented zip file and now everything works, including some gui bugs I was also experiencing. 

Thank you so much!

**Comment by loki79uk** [comment]
> Okay cool!
> Not sure why it worked as I just installed the -seemingly- same zip file from the above website and started having issues today. But I deleted the mod and the mod settings and downloaded your commented zip file and now everything works, including some gui bugs I was also experiencing. 
> 
> Thank you so much!

No problem, just avoid those websites in the future. There is no telling what they changed..

**Comment by cblain22** [comment]
Duly noted. I greatly appreciate your help and also your amazing mods! Keep it up
