### ISSUE TITLE
Loading area not showing.

### ISSUE THREAD

**Issue by WiiZSlee** [loki79uk/FS25_UniversalAutoload#148]
After loading the save, the box of the loading zone disappeared, delete the mod, updated for the last version, and stills not showing and not be able to edit the loading zone.

**Comment by WiiZSlee** [comment]
![image](https://github.com/user-attachments/assets/24a71c7e-fa18-4e7d-a73c-5884025fa4a5)

After deleting the mod, started the save without the mod, and install again, it still not working.

**Comment by loki79uk** [comment]
Can you attach you log file please?

**Comment by WiiZSlee** [comment]
> Can you attach you log file please?

how can i do it? xD

**Comment by loki79uk** [comment]
drag and drop the file from e.g.: `C:\Users\Loki\Documents\My Games\FarmingSimulator2025\log.txt`

**Comment by WiiZSlee** [comment]
[log.txt](https://github.com/user-attachments/files/18165394/log.txt)

**Comment by loki79uk** [comment]
Can you look at your mod settings xml and remove the two entries that do not have enterable passenger as the option:
```
2024-12-17 12:22 ADDING SHOP ITEM data/vehicles/international/cvSeries/cvSeries.xml
2024-12-17 12:22   >> data/vehicles/international/cvSeries/cvSeries.xml [2] 
2024-12-17 12:22   >> data/vehicles/international/cvSeries/cvSeries.xml [1] 
2024-12-17 12:22   >> data/vehicles/international/cvSeries/cvSeries.xml [2|1] (enterablePassenger)
```

**Comment by WiiZSlee** [comment]
![image](https://github.com/user-attachments/assets/5aa8a2bc-60d3-459a-bff7-52827c954f86)

u mean here?

**Comment by WiiZSlee** [comment]
The things is, its not only on the CV Series, is at all traillers

**Comment by loki79uk** [comment]
Yes, that empty one is the issue - when it loads that there is no loading area defined.  But you can deleted both, ad the enterablePassenger one is correct.

**Comment by loki79uk** [comment]
Can you attach the whole file?

**Comment by WiiZSlee** [comment]
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<universalAutoload>
    <vehicleConfigurations>
        <vehicle configFileName="data/vehicles/international/cvSeries/cvSeries.xml">
            <configuration selectedConfigs="2">
                <loadingArea offset="-0.000 1.022 -1.745" width="2.342000" length="3.870081" height="2.356430"/>
            </configuration>
            <configuration selectedConfigs="1"/>
            <configuration selectedConfigs="2|1" useConfigName="enterablePassenger">
                <loadingArea offset="-0.000 1.022 -1.745" width="2.342000" length="3.870083" height="2.793413"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/international/series200/series200.xml">
            <configuration selectedConfigs="1">
                <loadingArea offset="-0.000 0.923 -1.251" width="1.486404" length="2.508221" height="1.493576"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/demco/steelDropDeck/steelDropDeck.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.000 1.190 -2.730" width="0.555696" length="2.690280" height="0.567947"/>
                <loadingArea offset="-0.000 1.011 -0.296" width="2.471772" length="11.244407" height="3.973874"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/lodeKing/renownTriAxleBeavertailLowDrop/renownTriAxleBeavertailLowDrop.xml">
            <configuration selectedConfigs="ALL"/>
        </vehicle>
        <vehicle configFileName="data/vehicles/brantner/dd24073/dd24073.xml">
            <configuration selectedConfigs="1"/>
        </vehicle>
        <vehicle configFileName="data/vehicles/krone/profiLiner/profiLiner.xml">
            <configuration selectedConfigs="1"/>
        </vehicle>
        <vehicle configFileName="data/vehicles/lizard/multiPurposeTruck/multiPurposeTruck.xml">
            <configuration selectedConfigs="3">
                <loadingArea offset="0.000 0.958 -0.961" width="1.891418" length="3.585865" height="3.009211"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="FS25_schwarzmuellerTimberTrailerSemi/timberTrailerSemi.xml">
            <configuration selectedConfigs="ALL">
                <options isLogTrailer="true"/>
                <loadingArea offset="-0.014 1.243 0.799" width="1.304000" length="11.644770" height="3.110545"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/riedler/timberFrameFH16/timberFrameFH16.xml">
            <configuration selectedConfigs="1">
                <loadingArea offset="0.013 1.532 -1.112" width="2.061367" length="5.917993" height="4.150071"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/riedler/timberTrailer3A/timberTrailer3A.xml">
            <configuration selectedConfigs="ALL">
                <options isLogTrailer="true"/>
                <loadingArea offset="0.015 1.053 -1.184" width="2.064341" length="4.934531" height="3.956220"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/pittsTrailers/lt408L/lt408L.xml">
            <configuration selectedConfigs="ALL">
                <options isLogTrailer="true"/>
                <loadingArea offset="0.020 1.354 0.510" width="1.190837" length="9.438648" height="4.188597"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/ponsse/bison/bison.xml">
            <configuration selectedConfigs="ALL">
                <options isLogTrailer="true"/>
                <loadingArea offset="0.000 1.190 -2.730" width="0.555696" length="2.690280" height="0.567947"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/rottne/f20D/f20D.xml">
            <configuration selectedConfigs="ALL">
                <options isLogTrailer="true"/>
                <loadingArea offset="0.001 1.185 -3.335" width="0.797063" length="3.872248" height="0.798218"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/kesla/nd144/nd144.xml">
            <configuration selectedConfigs="2">
                <options isLogTrailer="true"/>
                <loadingArea offset="-0.003 0.851 0.103" width="0.093657" length="4.621469" height="0.151436"/>
            </configuration>
        </vehicle>
        <vehicle configFileName="data/vehicles/pfanzelt/rwgP13/rwgP13.xml">
            <configuration selectedConfigs="2">
                <options isLogTrailer="true"/>
                <loadingArea offset="-0.000 1.080 -0.549" width="0.859586" length="3.994865" height="0.869331"/>
            </configuration>
        </vehicle>
    </vehicleConfigurations>
</universalAutoload>

**Comment by WiiZSlee** [comment]
[UniversalAutoload.txt.zip](https://github.com/user-attachments/files/18165685/UniversalAutoload.txt.zip)

**Comment by loki79uk** [comment]
[UniversalAutoload.zip](https://github.com/user-attachments/files/18165780/UniversalAutoload.zip)

Try replacing the file with this one (after unzipping obviously)

**Comment by WiiZSlee** [comment]
![image](https://github.com/user-attachments/assets/5bb5b8e2-7b51-44e9-8df9-5bbe0ae746f6)
![image](https://github.com/user-attachments/assets/a0fe4858-4408-419e-9cbb-9c6d3c43f468)
![image](https://github.com/user-attachments/assets/66ad5bca-1dc4-4998-b857-12c8e39e0767)

Nope, nothing, i can edit the zones and nothing appears on the debug mode

**Comment by loki79uk** [comment]
Do the configured vehicles work now?  It looks like you are not buying the vehicle in the shop, just editing and then exiting.  Make sure you actually buy it.

**Comment by WiiZSlee** [comment]
The autoload works fine, but i cant use the debug mode and edit the zones on the shop.

**Comment by loki79uk** [comment]
> The autoload works fine, but i cant use the debug mode and edit the zones on the shop.

For debug mode, check your key bindings, maybe they conflict with something?

For editing in the shop you have to buy a new vehicle or apply changes in the workshop.  Exiting the menu without purchase is just like "cancel".  Or could be a conflict with FS25_Workshop, I have no idea what that mod does.

**Comment by WiiZSlee** [comment]
The FS25_Workshop is just a building, its not even active in my main save game. The bug begin when i started a multiplayer game and after that the debug mode does not appears and cant edit the zones.

**Comment by loki79uk** [comment]
Ahh, I missed that you are in MP!  Debug mode does not work in MP (see readme) and there are still issues applying changes that require a restart (see #69)

**Comment by WiiZSlee** [comment]
I know that the Debug dont work on MP, but the edit zone works, Im not on MP rigth now, i create a server and when i get back to the same save but on SP, the debug and the edit zone dont work. Supposedly I should be able to see the debug again on SP and the edit zone too.

**Comment by WiiZSlee** [comment]
If i start a new save, the debug dont work and the edit zone dont appears.

**Comment by loki79uk** [comment]
Is this for a trailer that you have previously configured?

**Comment by WiiZSlee** [comment]
For everything xD

**Comment by WiiZSlee** [comment]
how the debug zone are rendered? i change the render for directx 11

**Comment by loki79uk** [comment]
But the autoload functionality is working?  That makes no sense.  Can you send a SP screenshot in game to see what key bindings are active.

**Comment by loki79uk** [comment]
Can you delete the whole mod settings file (or move to desktop as backup), and then try again?

**Comment by WiiZSlee** [comment]
I will try to change the render back to Directx 12 and see if it works

**Comment by loki79uk** [comment]
I wonder if this is due to the non-ascii character - your path contains "Tomás" so maybe the same as https://github.com/loki79uk/FS25_UniversalAutoload/issues/7#issuecomment-2507767845

**Comment by WiiZSlee** [comment]
Nope, dont works, i dont think is due to the non-ascii bc it was working before xD

**Comment by WiiZSlee** [comment]
[UniversalAutoload.zip](https://github.com/user-attachments/files/18166525/UniversalAutoload.zip)

**Comment by loki79uk** [comment]
> [UniversalAutoload.zip](https://github.com/user-attachments/files/18166525/UniversalAutoload.zip)

So this was written after buying a vehicle in the shop, but there was no blue box displayed in the shop?  That seems impossible..  if the box dimensions are known they should be displayed.

**Comment by loki79uk** [comment]
> But they warent there xD This all happens after creating a MP Game, my GF joim (was shes 1st time using the mod) and when i comeback to SP the boxs disappear

can you send me her log file?

**Comment by WiiZSlee** [comment]
Mine
[log.txt](https://github.com/user-attachments/files/18168207/log.txt)

Hers
[log.txt](https://github.com/user-attachments/files/18168219/log.txt)

**Comment by loki79uk** [comment]
> Mine [log.txt](https://github.com/user-attachments/files/18168207/log.txt)
> 
> Hers [log.txt](https://github.com/user-attachments/files/18168219/log.txt)

the second one is 2 days old and on a different version (0.2.1.4 vs 0.2.2.0)

I really need to see both from the same time so that I can match up the events and try to see what is happening.

**Comment by WiiZSlee** [comment]
how can i see my past logs?

**Comment by WiiZSlee** [comment]
So, my GF can see the box, but i cant.

Mine
[log.txt](https://github.com/user-attachments/files/18168521/log.txt)

Hers
[log.txt](https://github.com/user-attachments/files/18168526/log.txt)

**Comment by WiiZSlee** [comment]
Maybe this is the problem?
![image](https://github.com/user-attachments/assets/caf22a5d-2b94-409b-81c8-12438eff3184)

**Comment by loki79uk** [comment]
You are talking about the blue box in the shop?

You have both gone back to the old version now: (Version: 0.2.1.4) FS25_UniversalAutoload

**Comment by WiiZSlee** [comment]
Yes, and the 0.2.1.4 was the version when we play together and the problem starts.

**Comment by loki79uk** [comment]
does your mod settings file contain this entry now?

```
2024-12-17 16:18 Creating NEW settings file C:/Users/Tomás/Documents/My Games/FarmingSimulator2025/modSettings/UniversalAutoload.xml
2024-12-17 16:18 FIND CORRECT SETTINGS FILE POSITION:
2024-12-17 16:18 configFileName = data/vehicles/international/cvSeries/cvSeries.xml
2024-12-17 16:18 selectedConfig = 2|1
2024-12-17 16:18 useConfigName = enterablePassenger
2024-12-17 16:18 SAVE TO SETTINGS FILE
2024-12-17 16:18 INSERT CONFIG INDEX #0
2024-12-17 16:18 USING CONFIG SUB-INDEX: #0 (2|1)
2024-12-17 16:18 useConfigName: enterablePassenger
2024-12-17 16:18 options:
2024-12-17 16:18 loadingAreas:
2024-12-17 16:18   >> .loadingArea(0)#offset = table: 0x000001ed06df5608 - 0 0 0
2024-12-17 16:18   >> .loadingArea(0)#width = 2.3420000076293945 - 0
2024-12-17 16:18   >> .loadingArea(0)#length = 3.87808620929718 - 0
2024-12-17 16:18   >> .loadingArea(0)#height = 2.3564376831054688 - 0
```

and how did you create that without seeing the blue box?

**Comment by WiiZSlee** [comment]
[UniversalAutoload.zip](https://github.com/user-attachments/files/18168761/UniversalAutoload.zip)

idk xD i cant even see the little box to edit

**Comment by WiiZSlee** [comment]
![image](https://github.com/user-attachments/assets/adbee4fb-753b-458a-ae93-afaebf9ae701)
![image](https://github.com/user-attachments/assets/ef69e963-b201-457d-9a05-b369adede688)
![image](https://github.com/user-attachments/assets/5a7d2548-b6b6-42fc-a98a-6889b6e3b304)

**Comment by loki79uk** [comment]
but why the blue lines are not showing is a mystery

**Comment by WiiZSlee** [comment]
i just re-configure him and insta add the load zone, without need to restart, I can send you my game configs and see if there's something wrong, I already comeback to d3d 12 so its not that, what a hell of a thing xD

**Comment by loki79uk** [comment]
> i just re-configure him and insta add the load zone, without need to restart

this makes no sense at all to me, can you write the exact steps of what you did from when the game loaded so I can understand

**Comment by WiiZSlee** [comment]
I opened the save, went with the CV to the shop and saw if there was a blue box, nothing, I reset the flatbed, there was no loading zone, I went to the shop, changed a setting, in this case, I removed the extension from the front, and it automatically created the loading zone, without the blue box appearing.

**Comment by WiiZSlee** [comment]
[UniversalAutoload.zip](https://github.com/user-attachments/files/18168945/UniversalAutoload.zip)
the new one with the flatbed

**Comment by loki79uk** [comment]
So yeah, it look slike everything is working as it should EXCEPT that you can't see the blue box at all?

**Comment by WiiZSlee** [comment]
Yes, and the debug mode in singleplayer.

[game.zip](https://github.com/user-attachments/files/18169167/game.zip)
 
My game config

**Comment by loki79uk** [comment]
I guess it could be if you are using lots of upscaling and DLSS or whatever.  Can you just reset your GFX settings and see if that works?

**Comment by WiiZSlee** [comment]
like this?
![image](https://github.com/user-attachments/assets/f03432d5-2ffc-42a9-963a-44ef4ac7031f)

stills nothing,

**Comment by WiiZSlee** [comment]
Its fixed!!! I only activate the TAA.
