### ISSUE TITLE
[Multiplayer] Load triggers not recognized

### ISSUE THREAD

**Issue by JasonX2001** [loki79uk/FS25_UniversalAutoload#15]
Hi,

i don't know if this is a multiplayer only probelm or a general with pallets. The triggers don't work some times, so it does not recognize the pallets until you once change the filter form whatever is set now, to another setting. Then the autoloader can "see" the pallets again and shows the load promts.

In my case i had to change it from "Only Full" to "All" and after the next run i had to change it from "All" to Only Full" to show me the prompts for loading. And then i could load/unload the pallets.

Its not a critical issue.

Using 0.0.0.4

**Comment by loki79uk** [comment]
it is a multiplayer issue - I think something to do with GIANTS optimising the trigger detection, or maybe they changed from FS22 and so I'm using them wrong now.  I found if you go and pick up the object with superstrength, then it is immediately detected.  I guess it raises some active or dirty flag.  Needs more investigation!

**Comment by dskaggs** [comment]
Was just in a MP game with my daughter that I was hosting from my machine.  She couldn't trigger autoloading, but if she got out of the vehicle and I got, I was able to trigger loading (pallets).

**Comment by loki79uk** [comment]
> Was just in a MP game with my daughter that I was hosting from my machine. She couldn't trigger autoloading, but if she got out of the vehicle and I got, I was able to trigger loading (pallets).

Yes, it seems to just be like this at times.. All the code is the same as SP and the same as it was in FS22.  It just seems to not work sometimes..  I might have to write my own methods to detect pallets instead of relying on GIANTS trigger callbacks.

**Comment by loki79uk** [comment]
I think this should be fixed now in the latest release:
https://github.com/loki79uk/FS25_UniversalAutoload/releases

Closing as completed, but please re-open if you still have issues.
