### ISSUE TITLE
Really Buggy on Dedicated Server

### ISSUE THREAD

**Issue by MultiKnacker** [loki79uk/FS25_UniversalAutoload#151]
The Autoload mod is really buggy on a dedicated Server. Problems occuring are:
- Need to reactivate with shift+r after each palette or bale
- Logs not really able to be loaded. It worked for one log but two others were not picked up
- When standing next to pallet can't choose what pallet to pickup. It always says there is no valid product there or something like that
- Sometimes not all controlls are listed on the top left

**Comment by loki79uk** [comment]
Have you restarted the server since buying them?  This is a known issue and I'm working on it #69

**Comment by MultiKnacker** [comment]
Yes I did. Another thing I noticed is that you need a good performing server. Hosted on sites like nitrado does not really work. I now have setup a server on my own server with 6 CPU cores and it seems to have solved the problem with the reactivating of the loading. So pretty resource intensive it seems

**Comment by loki79uk** [comment]
> Also do you have a solution for the menu not showing properly which type is selected to be loaded and unloaded (default by pressing z)?

What do you mean?  Can you post a screenshot?

**Comment by MultiKnacker** [comment]
![image](https://github.com/user-attachments/assets/802e6ab6-03c1-445a-921c-4cc22cb2f4ad)
This is always there. The menu to choose which type of resource to load does never appear. Currently there are only wooden beams but even when there are wood chips too it doesnt show to only load wood chips or the beams. When I press "z" I can choose what to load so the function does work but is not shown

**Comment by loki79uk** [comment]
The default for change fill type is "T".  That conflicts with talk in MP, so it sounds like you bound it to "Z" for some reason, but Z is open curtain on the KRONE, so I think you will have another conflict.

**Comment by MultiKnacker** [comment]
Probably because my keyboard layout is german I guess?

**Comment by MultiKnacker** [comment]
Now it's showing up. Yesterday it wasn't. Actually by now I have no idea if it's a mod issue or a game issue
![image](https://github.com/user-attachments/assets/3c21e2de-a873-4d17-bb84-9eab237762a0)

**Comment by loki79uk** [comment]
It is supposed to show up when something is either loaded or available.

**Comment by loki79uk** [comment]
I don't know about the key bindings, but the orginal issue should be resolved now after: https://github.com/loki79uk/FS25_UniversalAutoload/releases

**Comment by loki79uk** [comment]
Closing original issue as resolved now, but feel free to continue to comment here if you are still having issues with key bindings.
