### ISSUE TITLE
Need "NoLoadingIfFolded" option again

### ISSUE THREAD

**Issue by ScootersWorkbench** [loki79uk/FS25_UniversalAutoload#152]
I have a side by side that has an fillPlane and exactFillRootNode that is visible and "active" when the tailgate is up (Folded).   When I unfold the tailgate the exactFillRootNode moves under the vehicle so pallets of seeds or any bulk item does not fill the bed of the side by side.   In 22 it was nice because the F1 menu didn't show the AutoLoad options if the vehicle was folded and that flag was set.

**Comment by loki79uk** [comment]
Don't worry that is not an exhaustive list.  I'll still be adding more features to the menu.

**Comment by loki79uk** [comment]
Please try the latest version: https://github.com/loki79uk/FS25_UniversalAutoload/releases
