### ISSUE TITLE
Just a question! 

### ISSUE THREAD

**Issue by MrNic92** [loki79uk/FS25_UniversalAutoload#159]
Hey Loki, is it possible to add autoload to other vehicles or equipment that doesn't have tension belts, or is not a trailer, flatbed truck? I made an in-game forklift with autoload for Fs22 and I want to recreate it for fs25, I somehow made the autoload box appear in the shop to configure but the the wheels disappeared and could not enter the forklift. If you could answer that would be awesome! Thank you!

**Comment by loki79uk** [comment]
Basically no, in the current version the tension belts are required to define the load area.  I did have an unreleased dev version for FS22 that detected forklifts separately with the idea that it could load and unload known pallets from vehicles.  The issue is not only defining where on the forks pallets should go, but also that the forks only have a kinematic joint with the first pallet, not a stack.  I might spend some more time on it at some point, but not a priority until everything else is working.

**Comment by MrNic92** [comment]
Hmmm... I might have an idee... On making something... Do you know any video or have one on adding tension belts? I have searched like crazy and can't find one?

**Comment by loki79uk** [comment]
Do you mean by adding tension belts in GE?  Just copy a vehicle that has them.  The wider issue is what about wheel loaders and skid steers where you can use different sized forks, etc..  or maybe now the vehicle has a bucket instead.

**Comment by loki79uk** [comment]
> Is it possible to make the forks for the forklift a separate part? Like a attached tool? (sorry, I have all this ideas but I'm still a noob at modding).

Not for forklifts, but this is how the other vehicle types work - wheel loader, skid steer, etc.  I'm not really sure how this relates to UAL anymore?

**Comment by MrNic92** [comment]
Just some idea, making some kind of platform so then tension belts  work and define the loading area as you said,so then maybe the UAL will recognise it like it would with a normal trailer or flatbed truck. Hmm... So first I have to make the tension belt work as it should and then UAL will do as it would for a normal trailer...

**Comment by loki79uk** [comment]
> Just some idea, making some kind of platform so then tension belts work and define the loading area as you said,so then maybe the UAL will recognise it like it would with a normal trailer or flatbed truck. Hmm... So first I have to make the tension belt work as it should and then UAL will do as it would for a normal trailer...

yes, but that would be weird for a forklift - i.e. it would try to load multiple pallets, and unload onto the ground, etc..  I think what you want is a special script just for forklifts?

**Comment by MrNic92** [comment]
I'm not home right now, but when I get the chance I will sent you the mod for Fs22, i used the a Pallet Autoloader mod for that and added the triggers in GE and also used pallets for referince on where the pallet should be loaded and how many, and it worked.

**Comment by loki79uk** [comment]
> I'm not home right now, but when I get the chance I will sent you the mod for Fs22, i used the a Pallet Autoloader mod for that and added the triggers in GE and also used pallets for referince on where the pallet should be loaded and how many, and it worked.

Sure, if you edit a specific vehicle in GE and write a script using the special nodes - but the principle of Universal Autoload is that it should be universal.  I.e. it should work on all vehicles without needing to faff around in GE.  It is possible, just a lot of work, so I am not going to do it until everything else is done (as I said already in the first reply).

**Comment by MrNic92** [comment]
Thank you very much, you shed light over some questions I had, I think I'm going to start a project from scratch and see were that leads me, maybe a crazy idea 😅😅😅. Thank you for working so hard to make the UAL for everybody to enjoy! And I hope it's not a bother to ask your advice again sometimes.
