### ISSUE TITLE
Krone Profiliner Loading zone not showing up

### ISSUE THREAD

**Issue by CPTmorningW00d** [loki79uk/FS25_UniversalAutoload#160]
Hi Loki! 

Firstly, thank you so much for the great mod, I loved it before, and hope I can use it again soon!

However, when using the Profiliner (purchasing a new one after updating) I am not able to load any pallets. The loading zone seems to be configured correctly in the store.
When trying to load pallets, for instance in front of the sugar mill, greenhouse or sawmill, the profiliner only picks up 1 pallet around the middle of the truck. 

After pressing crtl + shift + f12 no loading zone is shown. I have deleted the modsettings file after every update, but nothing I try to change seems to help. 

Any idea's on what I can try? 

Note: I am playing on a G-Portal server.

**Comment by loki79uk** [comment]
Are you deleting the file on the server or locally?  It should work if you: 
1) configure in shop 
2) buy in shop 
3) restart server

**Comment by CPTmorningW00d** [comment]
It has not worked yet. I tried this several times. 

I have deleted the file on the server. Is there anything else I can try? If not, I will just wait it out.

**Comment by loki79uk** [comment]
Can you attach your server log from the last restart?

**Comment by CPTmorningW00d** [comment]
Ofcourse, I will send this when I am home! 

I'll also update first. Thanks Loki!

**Comment by loki79uk** [comment]
This should not happen anymore after the latest update (v0.3.0.0) https://github.com/loki79uk/FS25_UniversalAutoload/releases

**Comment by CPTmorningW00d** [comment]
Woah! That's nice Loki. I'm going to test it immediately. It seems like I was doing something wrong before. The vehicle configuration seemed to be ok, but it didn't work. 

It did later though!

**Comment by loki79uk** [comment]
> Woah! That's nice Loki. I'm going to test it immediately. It seems like I was doing something wrong before. The vehicle configuration seemed to be ok, but it didn't work.
> 
> It did later though!

What you described in the first post is exactly the expected behaviour before v0.3.0.0.  Buying a trailer in MP didn't apply the settings in time, so until you restarted the server you just got a small 1m x 1m box for each trigger.  See bug #69

**Comment by CPTmorningW00d** [comment]
You're exactly right. I didn't do it in the right order, I think... I got so frustrated xD

**Comment by loki79uk** [comment]
Sounds like this is resolved now.
