### ISSUE TITLE
Controller controls 

### ISSUE THREAD

**Issue by Erzmaster** [loki79uk/FS25_UniversalAutoload#163]
Hey, I love the mod! But for me, one big feature is missing. Controls for controller. I play with an XBox Controller on PC. But need to switch every time to my keyboard for autoload. 

Are you maybe able to add controls for a controller? 

As I think you do not play with a controller and maybe don’t have one with you, I made some suggestions which I think might work (tested with several trailers, found these buttons were always free):

Unload: RB+ Y
Load: RB + X
Tighten straps: RB + R (already implemented in base game)

Container Type: LB + Left 
Full/ Partial: LB + Down
Material type: LB + Right

Auto Bailing: LB + Y
Left/ right side unload: LB + X

Already in use for other trailer functions:
Swing open/ swing shut: LB + A
Open tarp on trailer: LB + Up

**Comment by loki79uk** [comment]
Can't you just bind these yourself in the menu?  I don't have a controller, but I thought that was how it works?

**Comment by Erzmaster** [comment]
You are right. I honestly thought this was just for the controls of the standard game, but not for mods. But never checked. Thanks, that works!
