### ISSUE TITLE
not loading wood

### ISSUE THREAD

**Issue by Dpatau** [loki79uk/FS25_UniversalAutoload#164]
im having this issue with it not wanting to load wood. iv followed multiple videos on setting up the trailer and everything but i have some odd text that they didnt on the wood, but i cant seem to read it. anyone had this issue 
![Uploading image_2024-12-19_203017607.png…]()

**Comment by Dpatau** [comment]
![Uploading Untitled.png…]()

**Comment by Dpatau** [comment]
i think it says position node@D0

**Comment by Dpatau** [comment]
![image_2024-12-19_203823115](https://github.com/user-attachments/assets/0ea4aaea-f79c-4034-b659-4b56822c8640)

**Comment by loki79uk** [comment]
You have a very old version, please update to the latest.

**Comment by Dpatau** [comment]
thanks for the fast reply, its working now, that's so odd though as i downloaded the latest one hahah must not of added the corr3ect on into my folder.
