### ISSUE TITLE
Problem when loading

### ISSUE THREAD

**Issue by NexDK** [loki79uk/FS25_UniversalAutoload#165]
it seems to work fine for some time, then next day it started to load like this ?

![20241219142338_1](https://github.com/user-attachments/assets/6490961d-13d6-490d-9baa-5bc642de74b2)

**Comment by loki79uk** [comment]
Is this SP or MP?  Can you please attach a log file.

**Comment by NexDK** [comment]
This is mp, where do i find the log ?

**Comment by loki79uk** [comment]
> This is mp, where do i find the log ?

if MP, sometimes just unstrapping and driving around a bit will allow them to move them into position.  That is just the way object positions synchronise in the GIANTS engine.

**Comment by NexDK** [comment]
i got it working again, by changing rim color on the trailer then it seems to work again :-)
