### ISSUE TITLE
Controller Back

### ISSUE THREAD

**Issue by Mikey-Y** [loki79uk/FS25_UniversalAutoload#170]
when i go to customize something then hit the back button on my controller it goes back twice Out of the machine and into the vehicles tab

**Comment by loki79uk** [comment]
I hate the GIANTS keybinding system so much, lol.. :D

Does it do the same if you use ESC?  Some other people tested on controller and it was working for them.

**Comment by Mikey-Y** [comment]
just tried and yea it does it for both esc and controller but not if i click it on the bottom right

**Comment by Mikey-Y** [comment]
[inputBinding.zip](https://github.com/user-attachments/files/18213137/inputBinding.zip)

**Comment by Mikey-Y** [comment]
Yea still does it

**Comment by loki79uk** [comment]
I don't understand - I can hold down ESC and it will only go back to the configuration page, so I don't think it can be repeat rate or anything.

**Comment by Mikey-Y** [comment]
yea idk just downloaded v0.3.0.0 and it works fine now

**Comment by loki79uk** [comment]
That is even weirder! I didn't change anything. I think the GIANTS key binding system just has a mind of its own..
