### ISSUE TITLE
Loading is buggy / not working??

### ISSUE THREAD

**Issue by raffnix97** [loki79uk/FS25_UniversalAutoload#171]
Idk, SHIFT + I wont load wood, idk where the problem is
![grafik](https://github.com/user-attachments/assets/e7b1baec-85d0-405c-b4c6-52d8c68a6d03)

**Comment by raffnix97** [comment]
![grafik](https://github.com/user-attachments/assets/ee5d65dc-9d1b-40f1-a263-331da8209b56)

**Comment by loki79uk** [comment]
Those logs look way to big for that loading area.  Try cutting them smaller, or make the load area bigger.

**Comment by loki79uk** [comment]
Also, if you have set up the rear trailer and are trying to load that, then you need to
1) select the attached trailer with "G" key
2) move forward to use the loading triggers of the rear trailer

![image](https://github.com/user-attachments/assets/3306330f-2e88-404f-8a90-1e24c4441baa)
![image](https://github.com/user-attachments/assets/9d6d2503-5f28-4692-ac57-ae87fd9815e2)

**Comment by raffnix97** [comment]
Okay ty, Ill try that

**Comment by loki79uk** [comment]
Everything looks normal to me in the screenshots, so closing this bug for housekeeping, but you can continue to comment on here if you still have any questions.
