### ISSUE TITLE
[v0.3] Autoload not working on dedicated server

### ISSUE THREAD

**Issue by BurcoGames** [loki79uk/FS25_UniversalAutoload#173]
For some reason I cannot get autoload to load anything onto any trailer in a dedicated server. I've tried changing the settings in the shop, tried a couple different trailers, nothing works. Log does show some LUA callstack errors, not sure what that's about.

[log.txt](https://github.com/user-attachments/files/18215230/log.txt)

![image](https://github.com/user-attachments/assets/0bc9db48-5d7c-47d1-b797-03dfc0504e75)

**Comment by loki79uk** [comment]
okay - I thought I tested some vehicles without a config name, but clearly not

**Comment by loki79uk** [comment]
Sorry about that, I've tested new one with KRONE and no pre-exisitng config and now works for me.  Please try latest release: https://github.com/loki79uk/FS25_UniversalAutoload/releases/tag/v0.3.0.1

**Comment by BurcoGames** [comment]
> Sorry about that, I've tested new one with KRONE and no pre-exisitng config and now works for me. Please try latest release: https://github.com/loki79uk/FS25_UniversalAutoload/releases/tag/v0.3.0.1

Did some relatively limited testing and it seems to work as intended now. Thanks!
