### ISSUE TITLE
Krone Profi Liner not loading palets

### ISSUE THREAD

**Issue by Hugoo1406** [loki79uk/FS25_UniversalAutoload#174]
When I try to load palets, the "shift + r" button doesn't appear on the F1 menu, if I try to press it, a message appears saying something similar to "object too big for this vehicle". Any idea on how ot fix it?

**Comment by Hugoo1406** [comment]
![image](https://github.com/user-attachments/assets/32093dd8-c28b-4404-a0ef-52c7c744948f)
Sorry for the spanish!

**Comment by loki79uk** [comment]
I think you need to have one of the sides open for the Krone, not the rear door.  I'll see if I can add a different message for that one.

**Comment by loki79uk** [comment]
What version are you on?  You shouldn't have any keys available to load or unload unless one of the sides is open.

**Comment by Hugoo1406** [comment]
> I think you need to have one of the sides open for the Krone, not the rear door. I'll see if I can add a different message for that one.

Yep, that solved it, thank you so much.

**Comment by Hugoo1406** [comment]
> What version are you on? You shouldn't have any keys available to load or unload unless one of the sides is open.

I'm using the newest. Found that if you spam shift + g + r, it shows that message.

**Comment by loki79uk** [comment]
Interesting about spamming keys, I'll see if I can reproduce it.  Closing as resolved.
