### ISSUE TITLE
0.3.0.2 Car Trailer coverd/uncoverd

### ISSUE THREAD

**Issue by MrSengy** [loki79uk/FS25_UniversalAutoload#176]
Hey Loki, 

The Stema Trius no longer allows the covering of the tarp using the key combination. Additionally, the folding of the side walls does not work either. I have already tried resetting it and purchasing it again.

**Comment by loki79uk** [comment]
Can you send me the log file - if there is a key binding conflict there should be a message in there about it.

**Comment by geeknessfr** [comment]
Tested on my game, the keys don't show up in help panel but they still work, I can open one side (Y key) or even pick which side to open (U key). (And they show up with the controller, as usual)

Screenshot without the keys in the panel, but with the trailer opened :
![image](https://github.com/user-attachments/assets/2c1f5438-5b0e-468a-b353-a7c778d36c2f)

Controls show up with the controller :
![image](https://github.com/user-attachments/assets/edbc790c-c2a0-4d69-9c1a-acfcf27f6754)

Default controls for the trailer, without UAL loaded : 
![image](https://github.com/user-attachments/assets/1a75001e-a07e-4001-a022-bebbb30b92e8)

**Comment by loki79uk** [comment]
I don't think there is anything I can do about this.  There is a limit to the numbe of key bindings that GIANTS will display on the F1 menu, and sometimes the keybindings just fail to work.  Resetting all keybindings, or deleting your `inputBinding.xml` file seems to help.  Try resetting the bindings and let me know if it works?

**Comment by Trivium1709** [comment]
Just to add to this since its the same trailer. I'm also unable to auto unload with this trailer which I assume its because it also acts as a tipper. Is this something you can change within the mod?

**Comment by loki79uk** [comment]
You can now use the latest version to totally disable UAL if that helps.  I don't know what else I can do, but you could try removing some of the UAL keybindings that you don't use.

**Comment by Trivium1709** [comment]
> You can now use the latest version to totally disable UAL if that helps. https://github.com/loki79uk/FS25_UniversalAutoload/releases
> 
> I don't know what else I can do, but you could try removing some of the UAL keybindings that you don't use.

Just to be clear, I was talking about auto unload pallets with the mod that doesn’t work, I want UAL enabled on the trailer. (not sure if I’m not understanding what you meant)

**Comment by loki79uk** [comment]
> Just to be clear, I was talking about auto unload pallets with the mod that doesn’t work, I want UAL enabled on the trailer. (not sure if I’m not understanding what you meant)

I was referring to the original bug, that if you remove some of the UAL keys that you don't use then the other key binding should show up.

I will probably disable UAL for anything with a fill volume (as this has).  It is currently commented out, since it is useful to test what works and what doesn't, but in FS22 there were issues with loading pallets that had a compatible fill type so they then unloaded themselves into the trailer.  If there are too many conflicts it would be easier to just disable it completely, but if we can find workarounds for all the issues then I'll keep it as an option, but maybe make it default DISABLED instead of enabled.

```lua
	if vehicle.spec_fillVolume and #vehicle.spec_fillVolume.volumes > 0 then
		local nFillVol = #vehicle.spec_fillVolume.volumes
		print(vehicle:getFullName() .. ": UAL - fill volumes (" .. nFillVol .. ")")
		for i, fillVolume in ipairs(vehicle.spec_fillVolume.volumes) do
			local capacity = vehicle:getFillUnitCapacity(fillVolume.fillUnitIndex)
			print("  [" .. i .. "] = " .. capacity)
		end
		spec.hasFillVolume = true
		-- isValidForAutoload = false
	end
```

**Comment by Trivium1709** [comment]
> > Just to be clear, I was talking about auto unload pallets with the mod that doesn’t work, I want UAL enabled on the trailer. (not sure if I’m not understanding what you meant)
> 
> I was referring to the original bug, that if you remove some of the UAL keys that you don't use then the other key binding should show up.
> 
> I will probably disable UAL for anything with a fill volume (as this has). It is currently commented out, since it is useful to test what works and what doesn't, but in FS22 there were issues with loading pallets that had a compatible fill type so they then unloaded themselves into the trailer. If there are too many conflicts it would be easier to just disable it completely, but if we can find workarounds for all the issues then I'll keep it as an option, but maybe make it default DISABLED instead of enabled.
> 
> ```lua
> 	if vehicle.spec_fillVolume and #vehicle.spec_fillVolume.volumes > 0 then
> 		local nFillVol = #vehicle.spec_fillVolume.volumes
> 		print(vehicle:getFullName() .. ": UAL - fill volumes (" .. nFillVol .. ")")
> 		for i, fillVolume in ipairs(vehicle.spec_fillVolume.volumes) do
> 			local capacity = vehicle:getFillUnitCapacity(fillVolume.fillUnitIndex)
> 			print("  [" .. i .. "] = " .. capacity)
> 		end
> 		spec.hasFillVolume = true
> 		-- isValidForAutoload = false
> 	end
> ```

Ok sorry that makes sense now haha. Yeah having that as an option could be great. I just don’t see the point of that trailer having a fill type in its flattest configuration, but that’s giants I guess lol I can test out tomorrow by uncommenting that line and see how that goes

**Comment by geeknessfr** [comment]
> Just to add to this since its the same trailer. I'm also unable to auto unload with this trailer which I assume its because it also acts as a tipper. Is this something you can change within the mod?

Adding some infos and screenshots to this issue...

On my game I can Load/Unload pallets with this trailer. (with UAL)

![image](https://github.com/user-attachments/assets/ca3d1bcf-9553-4ba8-9d7e-dba6a67e5757)
![image](https://github.com/user-attachments/assets/f8ff3029-4cfc-4a74-b9ac-53f46731c2d2)
_I opened the back flap to let you see pallets inside, but it works without opening it_

But with the **uncovered version**, I can't load BigBag Pallets... but other pallets work fine.
![image](https://github.com/user-attachments/assets/b3a8013e-a52e-4997-abcc-d6a7ecb721ad)
![image](https://github.com/user-attachments/assets/c14adebe-2af7-485e-9120-782b4436cc29)

As you can see, BigBags are greyed, but not sugar pallets. (But if I want I can fill the trailer with BigBags content...)

**Comment by loki79uk** [comment]
That is how it should work, and additionally if you do fill with one of the bulk fill types then it shouldn't let you load anything until empty again.

**Comment by MrSengy** [comment]
The issue was for this Trailer unfold on Key Z. I don't know why. But it works now. Sorry for wasting your time 😅

**Comment by loki79uk** [comment]
No problem - it is all part of testing what might happen in the cases I have not tested! (most of them..)
