### ISSUE TITLE
Conflict with Modhub mod : "Fliegl Timber Runner Autoload Wood"

### ISSUE THREAD

**Issue by kaufes** [loki79uk/FS25_UniversalAutoload#178]
Hi,

if in the store you deactivate your Autoload to use the one from the mod "Fliegl Timber Runner Autoload Wood" from the modhub, there is a conflict your autoload stay available when loading logs. Leasing or buying does not influence, both does not work.
Your mod prevents the other to function.
I love your mod for pallets and bales but for logs, I just prefer the one from the Fliegl trailer.
Many thanks for your commitment and work and hope that this will help you solve the issue !

BR

Kaufes

**Comment by loki79uk** [comment]
> Fliegl Timber Runner Autoload Wood

Are you using the latest version?  And disabling UAL in the shop befoer purchase?  This has only been a feature since the last release (12 hours ago) https://github.com/loki79uk/FS25_UniversalAutoload/releases

**Comment by loki79uk** [comment]
It works for me (i.e. purchase with UAL disabled and then the other woodloading works)

![image](https://github.com/user-attachments/assets/f820cec4-a23d-41bb-a115-c1f0a2eae5f9)

**Comment by kaufes** [comment]
> > Fliegl Timber Runner Autoload Wood
> 
> 
> 
> Are you using the latest version?  And disabling UAL in the shop before purchase?  This has only been a feature since the last release (12 hours ago) https://github.com/loki79uk/FS25_UniversalAutoload/releases

Yes : latest version downloaded this Morning (4 Hours ago) from Github and in the Shop went in the Autoload menu, Autoload was activated, deactivated it (First trigger => No and all Parameter below disappeared)
But I had the feeling that when hitting purchase/lease, the Blue Box appeared shortly
When using the trailer you have Both keybindings top left corner Showed (yours and the others) and it loads the Logs using the standard box from your mod and not the pattern defined in the other mods
Seems like deactivating Autoload in the menu is set but is not transmitted to the trailer

**Comment by loki79uk** [comment]
> > > Fliegl Timber Runner Autoload Wood
> > 
> > 
> > Are you using the latest version?  And disabling UAL in the shop before purchase?  This has only been a feature since the last release (12 hours ago) https://github.com/loki79uk/FS25_UniversalAutoload/releases
> 
> Yes : latest version downloaded this Morning (4 Hours ago) from Github and in the Shop went in the Autoload menu, Autoload was activated, deactivated it (First trigger => No and all Parameter below disappeared) But I had the feeling that when hitting purchase/lease, the Blue Box appeared shortly When using the trailer you have Both keybindings top left corner Showed (yours and the others) and it loads the Logs using the standard box from your mod and not the pattern defined in the other mods Seems like deactivating Autoload in the menu is set but is not transmitted to the trailer

Can you attach your log file from when you buy it?

**Comment by kaufes** [comment]
Ok, will send you this later,need to investigate deeper then, not possible now, I will also check the other mods I have on my game save (ca. 50, 3 from outside Modhub)

**Comment by kaufes** [comment]
ok, so after further investigations, Universal Autoload was indeed still activated, but I noticed the following things that seems to be the issue here:

1. when purchasing/leasing, making any changes to the configuration (even the colors) after setting the autoload parameter resets them to standard values, including the loading volume, without notice
2. when you get to the store to edit the purchased item, changing the autoload settings only is not recognized by the game as a customization, it is not possible to edit autoload without editing colors or configurations (and the autoload must be done last or they will be reset to the standards)

I can understand that you reset the parameters when the configuration is heavily changed, to avoid collision with an added front panel to a log trailer e.g. but changing colors or adding mudflaps does not interfere with the loading volume or the autoload parameters

**Comment by loki79uk** [comment]
> once you know that, you know how to work around these small hurdles, but that can be challenging and exhausting

It is there on the first section of the readme:
![image](https://github.com/user-attachments/assets/6061dd5d-f622-4e9f-a16f-6a410c522b9c)

**Comment by loki79uk** [comment]
> I can understand that you reset the parameters when the configuration is heavily changed, to avoid collision with an added front panel to a log trailer e.g. but changing colors or adding mudflaps does not interfere with the loading volume or the autoload parameters

Also, that was not a design choice - that is what the GAME does every time you change something it destroys the current vehicle in the shop and creates a new one.

The workshop mechanic is more of a worakround and test to see what is possible.  You should really just buy a new vehicle with the settings that you actually want, restart the game, and forget about it.  I will see if I can enable the button without changing other things, but if you change other things then the vehicle will reset, there is nothing I can do about that.

**Comment by kaufes** [comment]
I read that notice and I thank you for being quite clear and open concerning the known particularities, not everyone does that !
OK, I was not aware that this was a GAME feature, makes sense that you have to live with then.
Topic can be closed from my POV : Just make clear in the disclaimers, that the autoload settings need to be done last just before buying to avoid any resetting.

**Comment by loki79uk** [comment]
I'll add an extra line to the readme.  It is all part of a development build.  Nothing is final (or expected to work fully), but with more people helping with the testing I can find all the problems sooner than if it is just me on my own.

**Comment by kaufes** [comment]
Sure and that's why I created a Github account this morning only to be able to create the ticket to share my experience ! 
I really like your job and wanted to provide feedback to potentially make it better !
To be fully open, I'm neither fully satisfied with the other log autoload : 
- you must drive forward and backwards  to catch the logs that are then autoloaded on the fly and land partially on the other pile... ==> you request no speed and that's maybe annoying, but better I think  
- or move the logs to catch them but need super force then and that does not work all the time
- but the stacking is better and there are defined piles with defined lengths, the volume definition is nice but hard to apprehend in the workshop view : 20m length does not allow to make 4 piles of 5m logs

Your mod has from my POV a better detection but would need improvements on the stacking and arranging of the goods : 
- maybe a re-arrange possibility to group pallets of the same  goods together and optimize the loading (loading at the sawmill makes a mess for example and is clearly not optimized. I do not have ADHD but I already unloaded and reloaded selecting each good type separately to be able to load more than 5 pallets ^^)
- specific to logs, predefined loading volumes :  when trailer type is log trailer, add 2 parameters for stacking : 
      -log length : automatic (current programm and works for everything), 4m, 5m (contract logs) etc... (list all the length possible with a harvester e.g.)
      - if previous is not "automatic" then ask quantity of piles : 1 to 5
 ==> display the blue volume on the trailer (e.g. 4x5m on the modded Fliegl is possible but everyone needs to engineer the length needed, L=20m is not sufficient, is it L=21,5m with 0.5m between each pile or more or less ?) everyone can then check if it fits or not, maybe define X volumes that will be loaded one after the other. clearly 5x5m will not fit but at least we can see it

**Comment by loki79uk** [comment]
>     * maybe a re-arrange possibility to group pallets of the same  goods together and optimize the loading (loading at the sawmill makes a mess for example and is clearly not optimized. I do not have ADHD but I already unloaded and reloaded selecting each good type separately to be able to load more than 5 pallets ^^)

Pallets should be sorted by size before loading - what pallets are you loading where you can only load 5 at a time?
