### ISSUE TITLE
mod won't load empty Dewulf vegetable pallets

### ISSUE THREAD

**Issue by ZP-Young** [loki79uk/FS25_UniversalAutoload#179]
![abcc7df5-089f-449e-aa9a-e7f1250a52db](https://github.com/user-attachments/assets/55498d36-a54f-43b0-918c-de6409f4397e)
As shown in the screenshot, mod doesn't recognize empty carrot pallets while can load loaded pallets.
mod version: 0.3.1.0

**Comment by loki79uk** [comment]
You need to press "O" to toggle the loading filter from `FULL ONLY` to `ANY` - see also https://github.com/loki79uk/FS25_UniversalAutoload/issues/118
