### ISSUE TITLE
2025

### ISSUE THREAD

**Issue by xelf529** [loki79uk/FS25_UniversalAutoload#193]
ballen autoload mit strg shift r geht nicht wird auch nich als option angezeigt

**Comment by loki79uk** [comment]
You have to select "bale trailer" as the trailer type in the settings before you buy it.

**Comment by xelf529** [comment]
its workink thanks

Am Sa., 28. Dez. 2024 um 10:58 Uhr schrieb Loki_79 ***@***.***
