### ISSUE TITLE
Autoloading logs sometimes puts them partially outside loading areas

### ISSUE THREAD

**Issue by joscha999** [loki79uk/FS25_UniversalAutoload#196]
On Version 0.3.2.3 I encountered this problem:
![image](https://github.com/user-attachments/assets/46d5e052-a2ce-4c4b-96fb-83b2d76cfa32)
Looking at the middle of the trailer there's one log that was apparently loaded on the back loading zone but too far forward and partially outside the second zone. It seems like the back of the ~6m log is at the same position as the shorter end pieces loaded just before.

This is using the Schwarzmüller Timber Trailer Semi but I'm not sure if it's related to it specifically.
I'm using two 6.2m long loading zones to load 6m logs without having them interfere when loading short logs - this worked fine but at some point this bug appeared (I'm not 100% sure but this might be related to log loading changes in 0.3.0.3).

Attached is my UA modsettings, log (though it doesn't seem like it has much information in this case) and the save. If you load the save and tab into the Semi and then hit ctrl + R to autoload this issue will occur (tested on my end, happens every time I load the save).

For obvious reasons this requires the Schwarzmüller Timber Trailer Semi, other mods should not be necessary to load/repro the issue.

[2024_12_29_Autoload_Bug.zip](https://github.com/user-attachments/files/18270356/2024_12_29_Autoload_Bug.zip)

Thanks for looking into this!

**Comment by joscha999** [comment]
Adding more cases to this:
1. Driving forward and loading more logs after loading the save causes a bunch more logs to load weirdly.
2. After bringing away one load and taking more logs on this also happened with the forward loading zone: 
![image](https://github.com/user-attachments/assets/b448bdb4-2dba-41d7-9524-f4d7b6a304b5)

**Comment by loki79uk** [comment]
I thought htis might happen now - are there some messages in the log like:
```
EXCEEDED LAST ADDED LOAD LENGTH
```

I think it was the change I made to improve distribution

**Comment by joscha999** [comment]
Not present in the log I sent in the zip nor in my current log where this definitely happened again after restarting the game a few hours ago.

**Comment by loki79uk** [comment]
Okay, I reproduced it.  Tends to happen after loading the game with partially full trailer, or if moving to a new area because those new logs are not sorted by length vs those already loaded.  I'm going to be away for a week or so, but I will see if I can solve it before I go.

**Comment by loki79uk** [comment]
I think should be fixed now in latest release https://github.com/loki79uk/FS25_UniversalAutoload/releases

Note that it can still happen after loading the old savegame for the fist time, but after unloading/reloading the logs it shouldn't happen again as the "last loaded length" is now saved as part of the savegame.

**Comment by joscha999** [comment]
After moving about 80 trees worth of logs I can confirm this is fixed - thank you!
