### ISSUE TITLE
Autoload disappeared after resetting

### ISSUE THREAD

**Issue by a7xrandoms** [loki79uk/FS25_UniversalAutoload#20]
My trailer flipped over while full of pallets, so I reset it to the store. The autoload menu no longer appears and the trailer has lost the autoload feature.

**Comment by loki79uk** [comment]
I'm not surprised about that!  Thanks, I will add handling of resetting events to the list.

**Comment by loki79uk** [comment]
This appears to be resolved now.  Not sure exactly when, probably around the same time as leasing vehicles in v0.0.0.8, but I just reset a trailer at the shop and autoload was still working.

Closing as fixed.  Please re-open if there are any more issues with resetting.
