### ISSUE TITLE
Bug with vehicles like International CV Series

### ISSUE THREAD

**Issue by geeknessfr** [loki79uk/FS25_UniversalAutoload#21]
The International CV Series truck has 2 configurations : Day Cab and Crew Cab, this config makes the vehicle longer, so the loading area move back, but in the modSettings XML, only the last bought config is saved.

```XML
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<universalAutoload>
    <vehicleConfigurations>
        <vehicle configFileName="data/vehicles/international/cvSeries/cvSeries.xml">
            <configuration selectedConfigs="2">
                <loadingArea offset="0.000 1.021 -2.565" width="2.342000" length="3.878124" height="2.356552"/>
            </configuration>
        </vehicle>
    </vehicleConfigurations>
</universalAutoload>
```

![image](https://github.com/user-attachments/assets/8b60af03-7e51-46d3-bb94-b820e28e2bbd)

I don't know if there's other vehicles like that actually, but I think there could be a problem for future mods, maybe ?

**Comment by iAlreadyExist** [comment]
you can edit the loading area when you buying the vehicle

TO CONFIGURE LOADING ZONES:

    Use middle mouse click in the shop to activate editing
    Right click drag to move individual faces
    ALT-right click drag to move opposing faces (use this for width)
    SHIFT-right click drag to move the whole zone
    CTRL with any of the above for fine control
    SHIFT-CTRL middle mouse click to auto-calculate the zone from scratch (if you mess up)
    Configuration can be edited in mod settings XML (if you know what you are doing)

**Comment by geeknessfr** [comment]
> you can edit the loading area when you buying the vehicle
> 
> TO CONFIGURE LOADING ZONES:
> 
> ```
> Use middle mouse click in the shop to activate editing
> Right click drag to move individual faces
> ALT-right click drag to move opposing faces (use this for width)
> SHIFT-right click drag to move the whole zone
> CTRL with any of the above for fine control
> SHIFT-CTRL middle mouse click to auto-calculate the zone from scratch (if you mess up)
> Configuration can be edited in mod settings XML (if you know what you are doing)
> ```

Thanks, but it's not what I am saying.... lol .... the zone is correct when buying the vehicle....

It's just to let @loki79uk know the different configs doesn't save in the mod XML :)

**Comment by loki79uk** [comment]
At the moment I only support vehicles with `ConfigurationSets`.  In 22 I had special support for these non-standard configurations, but it is not a priority yet until everything else is working.  You can edit the xml to set the config name manually as before and it should load, but I have not tried as I don't even have any mod trailers downloaded yet.

**Comment by geeknessfr** [comment]
> At the moment I only support vehicles with `ConfigurationSets`. In 22 I had special support for these non-standard configurations, but it is not a priority yet until everything else is working. You can edit the xml to set the config name manually as before and it should load, but I have not tried as I don't even have any mod trailers downloaded yet.

It's not a mod, the truck is in game... I didn't test the Series 200, as it can have a toolbox or not on the back...

Actually I have 2 savegames, and I change the values in the XML because I have the 2 versions of the CV Series, and I will do the same for the Series 200 if it has the same problem, it's not a problem for me... I just wanted to let you know for later ^^

Anyway, thank you for your work ! ;)

**Comment by loki79uk** [comment]
Ahh, I see it now - I just assumed because in FS22 all GIANTS vehicles had proper ConfigurationSets.  I guess they either got lazy, or changed the internal documentation..  Either way, it will get added again as a feature, there is just more important stuff to get working first!

**Comment by loki79uk** [comment]
Should be fixed now in latest release (15) https://github.com/loki79uk/FS25_UniversalAutoload/releases

You should find that the old loading zones are forgotten, but you just need to treat them as new vehicles - either buy a new one or configure it in the workshop.  You can safely delete the old configurations (single number id) from your mod settings file.  The new ones will look like `"1|2"`, where 1 is the config set, and 2 is the cab configuration.
