### ISSUE TITLE
Autoload logs

### ISSUE THREAD

**Issue by Roby1164** [loki79uk/FS25_UniversalAutoload#22]
I tried everything, but without a solution, even though the trailer is enabled for autoload, it doesn't want to load the logs.
![Screenshot_32](https://github.com/user-attachments/assets/786f217d-ad5c-4222-8864-590c2f9cbdb9)

**Comment by geeknessfr** [comment]
> I tried everything, but without a solution, even though the trailer is enabled for autoload, it doesn't want to load the logs. !

As mentioned on the Readme, logs autoloading is not implemented yet :)
