### ISSUE TITLE
[Enhancement] Load lower layer first and move "up" from there

### ISSUE THREAD

**Issue by dskaggs** [loki79uk/FS25_UniversalAutoload#23]
What is the possibility to load the lowest "layer" first and then move to loading pallets on the layer above after that? For example, today I loaded 2x pallets of seeds onto the base-game International CV Series flatbed. The first pallet was loaded at the front of the bed on the driver's side. The 2nd was loaded on top of the first.

It would be nice to have had that 2nd pallet loaded at the front of the bed on the passenger side so that both pallets were on the same level.

Definitely not a show stopper but a suggestion for a future optimization.

Thank you for all your work bringing this to FS25!

**Comment by geeknessfr** [comment]
Hi,

In the controls settings, you have a key to "Toggle Horizontal loading" :

![image](https://github.com/user-attachments/assets/5b4c7cfd-b053-478f-a8af-65b9a074d08f)

Then you can switch from vertical to horizontal and have the first layer loaded before : 

![image](https://github.com/user-attachments/assets/3a1dd51a-806f-4aeb-82ca-c7fbec179db5)

**Comment by loki79uk** [comment]
I might add a default key for this.  Personally I use INSERT, but I know there is a shortage of unique spare keys for mods to use..

**Comment by dskaggs** [comment]
Oh smashing! Thanks for the heads up @geeknessfr ! I'll try that out in a bit when I get back to the desk.

**Comment by dskaggs** [comment]
Closing this as already implemented. Thank you very much!
