### ISSUE TITLE
will there be support for low loaders? Configuration in the store is already possible, but does not work

### ISSUE THREAD

**Issue by haamic** [loki79uk/FS25_UniversalAutoload#24]
in the store, low-loaders are displayed as autoload. 
i can also configure autoload there. but they don't work in the game.
is this option still available?
![ual-shop](https://github.com/user-attachments/assets/f8af0d04-4de5-498f-9f8e-3f83df417780)
![ual](https://github.com/user-attachments/assets/b9ba9cfc-2458-4ba6-80f0-74d19e09398e)

**Comment by loki79uk** [comment]
It should work, that is a bug.  Check your local settings xml for incomplete entries, and remove if there are any.  I'm rewriting a lot of this code right now, so it should not happen anymore.

**Comment by haamic** [comment]
Erstmal vielen Dank für deine Arbeit, die du investierst.  UAL ist sehr sehr hilfreich.
Muss ich nach jedem update die Anhänger neu kaufen? 
Ich hatte heute vormittag mit 0.0.0.4 und dem Farmtech DPW 1800 gespielt, nach dem update auf 0.0.0.5 oder 0.0.0.6 hat er nicht mehr funktioniert. Nach Verkauf und Neukauf funktionierte er wieder. 
Dann ist mir aufgefallen, das das beladen von aussen (zu Fuss) bei mir nicht funktioniert und sobald man wieder im Fahrzeug sitzt sind die Einstellungen wieder zurückgesetzt z.b. man stellt ein Material: Holzbalken, nach aus- und einsteigen steht das Material wieder auf "alle". Wäre schön, wenn sich irgendwann gemerkt würde, was vorher eingestellt war. 
Der Demco Steel Drop Tieflader funktioniert bei mir aber immer noch nicht, obwohl in der Fahrzeugliste nun der zusatz - UAL 'xxxxx svorhanden ist.
Aber das wird schon noch....

**Comment by haamic** [comment]
> Erstmal vielen Dank für deine Arbeit, die du investierst. UAL ist sehr sehr hilfreich. Muss ich nach jedem update die Anhänger neu kaufen? Ich hatte heute vormittag mit 0.0.0.4 und dem Farmtech DPW 1800 gespielt, nach dem update auf 0.0.0.5 oder 0.0.0.6 hat er nicht mehr funktioniert. Nach Verkauf und Neukauf funktionierte er wieder. Dann ist mir aufgefallen, das das beladen von aussen (zu Fuss) bei mir nicht funktioniert. 
Und sobald man wieder im Fahrzeug sitzt sind die Einstellungen wieder zurückgesetzt z.b. man stellt ein Material: Holzbalken, nach aus- und einsteigen steht das Material wieder auf "alle". Wäre schön, wenn sich irgendwann gemerkt würde, was vorher eingestellt war. 
Der Demco Steel Drop Tieflader funktioniert bei mir aber immer noch nicht, obwohl in der Fahrzeugliste nun der zusatz - UAL 'xxxxx vorhanden ist. Ich seh keine Trigger links und rechts vom Trailer, wenn ich F5 drücke. Aber das wird schon noch....

**Comment by loki79uk** [comment]
> Erstmal vielen Dank für deine Arbeit, die du investierst. UAL ist sehr sehr hilfreich. Muss ich nach jedem update die Anhänger neu kaufen? Ich hatte heute vormittag mit 0.0.0.4 und dem Farmtech DPW 1800 gespielt, nach dem update auf 0.0.0.5 oder 0.0.0.6 hat er nicht mehr funktioniert. Nach Verkauf und Neukauf funktionierte er wieder. Dann ist mir aufgefallen, das das beladen von aussen (zu Fuss) bei mir nicht funktioniert Der Demco Steel Drop Tieflader funktioniert bei mir aber immer noch nicht, obwohl in der Fahrzeugliste nun der zusatz - UAL 'xxxxx vorhanden ist. Ich seh keine Trigger links und rechts vom Trailer, wenn ich F5 drücke. Aber das wird schon noch....

Check that it is not the same issue as here: https://github.com/loki79uk/FS25_UniversalAutoload/issues/28

**Comment by haamic** [comment]
bezieht sie die Antwort auf den demco oder die durch updates nicht mehr funktionierenden trailer?

**Comment by loki79uk** [comment]
> bezieht sie die Antwort auf den demco oder die durch updates nicht mehr funktionierenden trailer?

Yes, I think it is likely to be the same issue.  You probably need to remove the entry in your mod settings file (or delete the whole file and start again).

it might look like this:
```xml
        <vehicle configFileName="data/vehicles/demco/steelDropDeck/steelDropDeck.xml">
            <configuration selectedConfigs="ALL">
            </configuration>
        </vehicle>
```
instead of
```xml
        <vehicle configFileName="data/vehicles/demco/steelDropDeck/steelDropDeck.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="-0.000 1.444 7.020" width="2.471781" length="3.371630" height="2.509209"/>
                <loadingArea offset="-0.000 1.011 -0.300" width="2.471770" length="11.252068" height="2.474754"/>
            </configuration>
        </vehicle>
```

**Comment by loki79uk** [comment]
I'm sure this is fixed now - I think probably a settings bug from an earlier version.  Closing as can't reproduce/works for me.
