### ISSUE TITLE
Dedicated server problem 

### ISSUE THREAD

**Issue by TonyMontana23891** [loki79uk/FS25_UniversalAutoload#25]
The mod is not working on dedicated server (4net players server host) there is problem autoload function dosent work . Once im in shop i can change the blue box shape/ postion but after buying the trailer once i come near by bales or palets or big bags it dosent do anything

**Comment by loki79uk** [comment]
Good timing - please try the latest version:
https://github.com/loki79uk/FS25_UniversalAutoload/releases

BUT please read all of the release notes - there is still an issue where objects are not detected until you move them around.  I don't understand why yet, something to do with dirty flags.  The triggers that work fine in single player (and in FS22 MP) are just not detecting objects as they should.

**Comment by TonyMontana23891** [comment]
Omg i will

**Comment by Bolsonn98** [comment]
There is progress because I already have the option on the left side of the screen, but I can't stay awake, which is doing something wrong :(

**Comment by loki79uk** [comment]
There are general issues with MP that are unrelated to being a dedicated server, see also: https://github.com/loki79uk/FS25_UniversalAutoload/issues/27  I will be working on this ASAP, but I have some IRL stuff to do now for the rest of today.

**Comment by Bolsonn98** [comment]
I hope, good luck

**Comment by Tsumiki-Chan** [comment]
Unfortunately it still doesn't seem to work on MP. We see the options for Filters but we can't cycle through them (No Compatible Goods-Warning) and we don't get an option to load.

**Comment by loki79uk** [comment]
> Unfortunately it still doesn't seem to work on MP. We see the options for Filters but we can't cycle through them (No Compatible Goods-Warning) and we don't get an option to load.

Check the xml in mod settings - if there is a partially complete entry, then you need to remove it and reload the game.  Will look something like:
```xml
        <vehicle configFileName="data/vehicles/piaggio/ape50/ape50.xml">
            <configuration selectedConfigs="ALL">
            </configuration>
        </vehicle>
```

instead of 
```xml
        <vehicle configFileName="data/vehicles/piaggio/ape50/ape50.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.000 0.553 -0.689" width="1.128035" length="1.350709" height="1.091209"/>
            </configuration>
        </vehicle>
```

**Comment by loki79uk** [comment]
If not that, then you have to move the pallets around to get the game to refresh them, either by hand (with strength), or just crash into them.  As I've said already, see also: https://github.com/loki79uk/FS25_UniversalAutoload/issues/27

**Comment by Tsumiki-Chan** [comment]
> > Unfortunately it still doesn't seem to work on MP. We see the options for Filters but we can't cycle through them (No Compatible Goods-Warning) and we don't get an option to load.
> 
> Check the xml in mod settings - if there is a partially complete entry, then you need to remove it and reload the game. Will look something like:
> 
> ```
>         <vehicle configFileName="data/vehicles/piaggio/ape50/ape50.xml">
>             <configuration selectedConfigs="ALL">
>             </configuration>
>         </vehicle>
> ```
> 
> instead of
> 
> ```
>         <vehicle configFileName="data/vehicles/piaggio/ape50/ape50.xml">
>             <configuration selectedConfigs="ALL">
>                 <loadingArea offset="0.000 0.553 -0.689" width="1.128035" length="1.350709" height="1.091209"/>
>             </configuration>
>         </vehicle>
> ```

There doesn't seem to be any xml in the modsettings. Moving the Pallets around didn't help either

**Comment by TonyMontana23891** [comment]
i just want to let you know it only loads one bale out of 3 i tried 0.0.0.6 version 

![photo1](https://github.com/user-attachments/assets/71778816-559a-4c70-b054-9303449eed9f)

**Comment by TonyMontana23891** [comment]
![photo2](https://github.com/user-attachments/assets/eebad1b4-816f-4c33-9f04-8c8d5a95b93b)

**Comment by TonyMontana23891** [comment]
![photo2](https://github.com/user-attachments/assets/26c4446d-ecba-46dd-a2a8-36dbca7f4be0)

**Comment by FarmerTreanor** [comment]
Currently using the latest version 0.0.0.7 on MP to see if current issue still around having bought a trailer supported by the mod was given option load the wool, but it only loaded 1 pallet out the 7, so unloaded the wool and did another area again 1 pallet out 7. Then unloaded and now unable to load any pallets or bales as the option to load items no longer shows on the F1 menu.

**Comment by loki79uk** [comment]
Should be fixed now in the latest release: https://github.com/loki79uk/FS25_UniversalAutoload/releases

**Comment by FarmerTreanor** [comment]
Ok I take a look thank you for letting me know

**Comment by FarmerTreanor** [comment]
Yes seem to be fixed have the option to load the pallets, only item we noticed so far is the loading trigger to be little odd but we can work with that.

**Comment by TonyMontana23891** [comment]
i dint test it on last version but i will test it some more when i have time and will let you know some inforamtion how its behaving on dedicated mp server :D thanks for regular updates and hard work , for now im using super strenght to load my palets by hand :P

**Comment by TonyMontana23891** [comment]
> > i dint test it on last version but i will test it some more when i have time and will let you know some information how its behaving on dedicated mp server :D thanks for regular updates and hard work , for now im using super strenght to load my palets by hand :P
> 
> With LumberJack I hope :P

actually lumberjack is also not working on dedicated server hehe im using some other superstrenght mod from mod hub

**Comment by loki79uk** [comment]
> > > i dint test it on last version but i will test it some more when i have time and will let you know some information how its behaving on dedicated mp server :D thanks for regular updates and hard work , for now im using super strenght to load my palets by hand :P
> > 
> > 
> > With LumberJack I hope :P
> 
> actually lumberjack is also not working on dedicated server hehe im using some other superstrenght mod from mod hub

Get the latest from GitHub and it does.  Currently in testing for ModHub.

**Comment by TonyMontana23891** [comment]
Thank you 😊

**Comment by TonyMontana23891** [comment]
> > > > i dint test it on last version but i will test it some more when i have time and will let you know some information how its behaving on dedicated mp server :D thanks for regular updates and hard work , for now im using super strenght to load my palets by hand :P
> > > 
> > > 
> > > With LumberJack I hope :P
> > 
> > 
> > actually lumberjack is also not working on dedicated server hehe im using some other superstrenght mod from mod hub
> 
> Get the latest from GitHub and it does. Currently in testing for ModHub.

Hello dear Friend after some testing same result happens only loads one or two pallets , i have few photos from my dedicated server , i will send also game log from server 
![5](https://github.com/user-attachments/assets/39893fa4-b3af-45a7-bb52-49853fc2ed0d)
![4](https://github.com/user-attachments/assets/2b558f49-1234-4771-b3f5-63fa822f3258)
![3](https://github.com/user-attachments/assets/5e43cd9e-19ec-474e-a4d8-4570617a6795)
![2](https://github.com/user-attachments/assets/ceb867c5-11e2-43f8-9901-47980b1a022b)
![1](https://github.com/user-attachments/assets/116e95bc-e3b9-4e27-a8c2-65a76b419927)
[game log.txt](https://github.com/user-attachments/files/18051754/game.log.txt)

**Comment by TonyMontana23891** [comment]
[game log.txt](https://github.com/user-attachments/files/18051777/game.log.txt)
![test2](https://github.com/user-attachments/assets/4b88a0d4-3e61-4cc5-a19b-51be871fc805)

After short test it seems to work but in a strange way in only loads 2 pallets then i need to drive around and stop until it showes the load trigger , then it loads 2 more pallets , then drive around pallets the trigger appears and once more 2 pallets load . so only need to drive around pallets to load it to truck , loads 2 pallets then once more 2 pallets 
i hope my feed back helps

**Comment by loki79uk** [comment]
If this is on MP, then it sounds like the same as https://github.com/loki79uk/FS25_UniversalAutoload/issues/69

Does it still happen after a save and restart of the server?

**Comment by TonyMontana23891** [comment]
> If this is on MP, then it sounds like the same as #69
> 
> Does it still happen after a save and restart of the server?

let me try

**Comment by TonyMontana23891** [comment]
[game log.txt](https://github.com/user-attachments/files/18051833/game.log.txt)
ok i just saved game i will restart server
[after save txt.txt](https://github.com/user-attachments/files/18051848/after.save.txt.txt)
![new after save test2](https://github.com/user-attachments/assets/bb1ffeba-33e3-45dd-9ecc-c4d3f5710fb1)
![new after save test1](https://github.com/user-attachments/assets/500fcde4-1240-42e8-92cf-70697c8bb9a6)
As you see after i saved the game and restared the server it loads all the pallets at once , i will keep playing today but i think its working fully as intended , thanks for your support and fast feedback .. so saving game and restarting the server fixes issues

**Comment by TonyMontana23891** [comment]
![new after save test3](https://github.com/user-attachments/assets/98384d25-c661-40f6-b368-dc687154c219)
it works with wood beams , only small suggestion if its possible to fill this space with two more longer pallets 
![new after save test4](https://github.com/user-attachments/assets/3c88a0e2-dc94-45e5-a76d-0e19e1492c32)

**Comment by TonyMontana23891** [comment]
![Uploading new after save test5.png…]()

**Comment by loki79uk** [comment]
Those look too wide for the space.  If you set the width wider than the trailer in the shop then it will allow overhang.  If you go too wide then things will fall off of course!
