### ISSUE TITLE
Only Farmtech DDK2400 is working

### ISSUE THREAD

**Issue by JIIIK** [loki79uk/FS25_UniversalAutoload#28]
I just loaded the Version 0.0.0.6. i tried all trailers in singleplayer in a new game with only this mod. only works on Farmtech DDK 2400. I tried all possible trailers. For all trailers it gives me the autoload mechanic in the shop. but it will only work on the ddk 2400.

**Comment by loki79uk** [comment]
Check your mod settings xml, or best to delete that and start again. When it gets corrupted then the vehicles are loaded without loading zones.

it might look like this:
```xml
        <vehicle configFileName="data/vehicles/piaggio/ape50/ape50.xml">
            <configuration selectedConfigs="ALL">
            </configuration>
        </vehicle>
```

instead of 
```xml
        <vehicle configFileName="data/vehicles/piaggio/ape50/ape50.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.000 0.553 -0.689" width="1.128035" length="1.350709" height="1.091209"/>
            </configuration>
        </vehicle>
```

**Comment by loki79uk** [comment]
Please try v0.0.0.7: https://github.com/loki79uk/FS25_UniversalAutoload/releases

but be aware that new vehicles might still have the issue.  I will fix it tomorrow.

**Comment by JIIIK** [comment]
So i tried it again with 0.0.0.7. No changes. i tried new trailer, old trailer, and new trailer (with CTRL+Shift+middle mouse). All the same. seems like working area too small, see screenshot. Only works with ddk 2400 for me.
![Bild_2024-11-30_180410749](https://github.com/user-attachments/assets/316b30bf-6a20-4bf7-ae27-aa5f0d334a48)

![Screenshot 2024-11-30 180250](https://github.com/user-attachments/assets/02ce9796-81a9-4d35-aa06-e9ebdaa79b38)

**Comment by loki79uk** [comment]
Can you attach your mods settings XML please

**Comment by JIIIK** [comment]
![Bild_2024-11-30_181654053](https://github.com/user-attachments/assets/cc57bfd0-1eba-4b30-aae8-0528aa720ef4)
 hope this is the one u need. let me know if u need anything else

**Comment by ScootersWorkbench** [comment]
Just to add additional context here:   I cannot get any vehicle to work and I do not have a UniversalAutoload.xml in my modsettings folder.   I have the eShop version, not the steam version if that would make any difference.   I have loaded the newest version  0,0.0.7,  saved the game many times and quit and restarted and still no XML is created.

**Comment by jawo89** [comment]
> Just to add additional context here: I cannot get any vehicle to work and I do not have a UniversalAutoload.xml in my modsettings folder. I have the eShop version, not the steam version if that would make any difference. I have loaded the newest version 0,0.0.7, saved the game many times and quit and restarted and still no XML is created. Also, I am running the 1.3 patch.

I report the same problem, no xml file was created in Modsettings

**Comment by loki79uk** [comment]
> > Just to add additional context here: I cannot get any vehicle to work and I do not have a UniversalAutoload.xml in my modsettings folder. I have the eShop version, not the steam version if that would make any difference. I have loaded the newest version 0,0.0.7, saved the game many times and quit and restarted and still no XML is created. Also, I am running the 1.3 patch.
> 
> I report the same problem, no xml file was created in Modsettings (eShop version too, newest version and newest patch)

Are you buying the vehicle, or leasing it?

**Comment by loki79uk** [comment]
> Just to add additional context here: I cannot get any vehicle to work and I do not have a UniversalAutoload.xml in my modsettings folder. I have the eShop version, not the steam version if that would make any difference. I have loaded the newest version 0,0.0.7, saved the game many times and quit and restarted and still no XML is created. Also, I am running the 1.3 patch.

are you buying a vehicle?  the settings are only created and saved when you buy a vehicle.

**Comment by jawo89** [comment]
> > > Just to add additional context here: I cannot get any vehicle to work and I do not have a UniversalAutoload.xml in my modsettings folder. I have the eShop version, not the steam version if that would make any difference. I have loaded the newest version 0,0.0.7, saved the game many times and quit and restarted and still no XML is created. Also, I am running the 1.3 patch.
> > 
> > 
> > I report the same problem, no xml file was created in Modsettings (eShop version too, newest version and newest patch)
> 
> Are you buying the vehicle, or leasing it?


I confirm. it's like you say, everything works as long as you buy it. Thank you.

**Comment by JIIIK** [comment]
ok, so, buying a trailer is the way. now works as it should! thank you. so leasing is a problem at the moment but buying is working properly.

**Comment by jawo89** [comment]
All you have to do is buy it in a test world, a file will be created, and then you can start borrowing in your main save as well.

**Comment by loki79uk** [comment]
The latest version will save settings for all of buying, leasing or editing in the workshop.  In a future version there will hopefully be buttons with names so you actually know what is going on!  Closing as fixed.
