### ISSUE TITLE
0.007 (and previous) doesn't seem to work at all on a Mac

### ISSUE THREAD

**Issue by matt-screed** [loki79uk/FS25_UniversalAutoload#33]
I'm working with the latest MacOS on a newish iMac.  The game ran quite nicely, and still does, but autoload does not work at all.  No matter what I put the trailer beside it says 'no compatible goods are available' or whatever the exact message is.  When I press T or Y I get that message, LShift-R doesn't do anything.  I've tried a couple different trailers and trucks and no luck.  I can see the load box in the store, and I can adjust it.

I am on FS25 1.3, 24" 2023 iMac with M3 chip running Sequoia 15.1.1

**Comment by JanRehse** [comment]
I can confirm that it runs on my MacBook Pro Max M3 , but only with new trailers. For the trailers I already had, I had to modify them in the workshop so they would work.

**Comment by matt-screed** [comment]
Thanks for that info.  I replaced the trailers I had with fresh ones from the store, and it did say autoload there.  When I have the trailer, it shows me the autoload keys in the panel (top left of the screen, not sure what it’s called).  I pull up beside stuff, hit the Shift-R and nothing happens.  T and y give the message that there isn’t anything for it to work with.  Tried bales, big bags and a couple different pallets and it just ignores.   

Anyway, thanks again!

**Comment by loki79uk** [comment]
There is an issue with non ASCII characters where settings are not saved, I wonder if this is related?  Can you attach the XML file from your mod settings folder.

**Comment by matt-screed** [comment]
There’s a chance I’m an idiot and missed something.  i looked in mod settings and there was only one xmlfile, for lumberjack.  Then it occurred to me that I had leased the equipment.  So I bought one and it works great.  Thanks for taking the time to respond, you must be crazy busy.  If there was something that said it would only work on a purchase, I missed iit!

**Comment by loki79uk** [comment]
It will save settings now for buying, leasing and workshop editing.  I used a different method at one point (hooking into the buy event), but when I changed that we lost the leasing option.  Closing as fixed.
