### ISSUE TITLE
v0.0.0.7 - Some pallets are disappearing through the ground

### ISSUE THREAD

**Issue by geeknessfr** [loki79uk/FS25_UniversalAutoload#35]
Ok, I said I’d wait for some random little bugs, but it just happened while I was testing other things! 😅
So, I made a video, but it’s easier to explain if I show you frame by frame...

**This issue occurs whenever another pallet is positioned too close to the trailer while unloading.**
The proximity seems to cause the pallet to be detected as "on the trailer" and glitch and fall through the ground when "unloaded".

1 - I’m about to unload the trailer using Shift-I, and you can see an empty box representing the pallet on the other side of the trailer.

![PotPlayerMini64_AL9bVDgJHb](https://github.com/user-attachments/assets/fdf63766-491e-431a-9e30-efc2739752ad)

2 - When I press Shift-I, the pallets unload on the left side of the trailer. However, the pallet on the right side "disappears" and is unloaded on the left side instead. The problem is that the pallets on the left start falling on the ground, causing this pallet to clip through the ground.

![PotPlayerMini64_64PpEpjUHD](https://github.com/user-attachments/assets/c0f03058-24ec-4fdc-b272-21f0f3f4aa85)

3 - At this point, the pallets continue falling on the ground.

![PotPlayerMini64_sjvkQRnbsc](https://github.com/user-attachments/assets/6104443c-fb0c-47b4-af96-c0dcea095ff7)

4 - And finally, the pallet is completely gone.

![PotPlayerMini64_ydD4cm9QBv](https://github.com/user-attachments/assets/b3ecf2eb-adf2-42ae-9a82-3308c1b7aa7f)

**Comment by loki79uk** [comment]
Okay that is a new one!  They are supposed to be unloaded just above ground level.  In 22 I checked for collisions before allowing unloading.  I took that out of 25 for now because the new GIANTS implementation of collision detection was randomly reporting stuff that wasn't there and prevented unloading on open clear ground.  It is definitely one of the things I will try to fix before the first full release.

**Comment by geeknessfr** [comment]
I didn’t realize GIANTS’ engine had that kind of collision detection built-in—I honestly thought the mod was handling the detection itself. Makes sense now why it’s behaving that way, it sounds like their implementation is causing more headaches than it solves 😅.

Shrinking the box a bit sounds like a solid workaround for now, especially if GIANTS take their time fixing the core issue. At least it would prevent weird cases like this one or others...

Let me know if you need more testing on this or if there’s anything specific you’d like me to try out.

**Comment by loki79uk** [comment]
They provide an engine function that triggers a callback when objects enter and leave a volume, but it is not behaving like it did in FS22. :(

**Comment by loki79uk** [comment]
GitHub auto-closing bugs again..  Still, this should be fixed now.
