### ISSUE TITLE
v0.0.0.7 "Blue Box" not showing

### ISSUE THREAD

**Issue by DimesRFT** [loki79uk/FS25_UniversalAutoload#36]
Hi, I love your work! 
In the store, the blue box is not showing, I tried to remove and re-install the mod, but it still not showing. I tried all the mouse and keyboard short cuts, no luck. 

However, when I change the configuration, some other yellow boxes pop up near the tires, for less than 0.1 seconds and then disappear. I tried to record the gif but failed, its too quick. 

![image](https://github.com/user-attachments/assets/9539951e-443f-4b98-bacd-8e306fbc2ebe)

**Comment by haamic** [comment]
Does a reset work?
Reset = left shift+ctrl+mouse middle button

**Comment by DimesRFT** [comment]
> Does a reset work? Reset = left shift+left ctrl+mouse middle button
Hi, I tried ctrl+shift+mouse-mid-button, it didn't work, but shift-ctrl-mouse-mid-button. My bad, I didn't pay attention to the sequence of keys
