### ISSUE TITLE
not able to load 180cm round bales

### ISSUE THREAD

**Issue by qanadin** [loki79uk/FS25_UniversalAutoload#38]
I am getting the following message when attempting to load round bales that are 180cm

No compatible goods are available for loading or unloading

**Comment by loki79uk** [comment]
Which trailer? If you can load other pallets and not 180 bales then you just need to increase the width.  Have a look in the mod settings file and see what number is set for width.  You can actually just increase it there and reload the game, or edit in the shop.

**Comment by qanadin** [comment]
DPW 1800.  I just increased the width at the shop, gonna test it out now.

**Comment by qanadin** [comment]
I have increased the width and still nothing.  What mod setting file am I looking for that I can increase the width?

**Comment by loki79uk** [comment]
> I have increased the width and still nothing.  What mod setting file am I looking for that I can increase the width?

It is called UniversalAutoload.xml in the mod settings folder, in the same directory as your savegames.

**Comment by qanadin** [comment]
This is what I have it set to.  I don't know how much wider I need to set it at this point, its already almost double the size of the trailer when looking at it via the shop:

**Comment by loki79uk** [comment]
That is a config from FS22.  This mod is for FS25 - are you editing the wrong one?  or did you mean FS22?

**Comment by SnakeManPMC** [comment]
I have loaded several dozen 5,500 liter grass bales to fliegl DPW 180-something tractor pulled trailer without issues. Yes these are 150cm round bales, not 180cm as issue creator reports. Just wanted to give further reference that at least with 150cm round bales there are no issues. Neither sheep barn wool pallets, or production chains pallets like greenhouses and spinnery fabric etc.

**Comment by qanadin** [comment]
Okay so oddly enough, when the .zip is in the mods folder it isn't recognizing it.  But when extracted it does.  When it is extracted it doesn't put a file in the save game.  I am using Steam on MacOS if that makes a difference.

**Comment by loki79uk** [comment]
> Okay so oddly enough, when the .zip is in the mods folder it isn't recognizing it. But when extracted it does. When it is extracted it doesn't put a file in the save game. I am using Steam on MacOS if that makes a difference.

Have you downloaded the source code instead of the mod?  Look on the releases page, under "assets"
https://github.com/loki79uk/FS25_UniversalAutoload/releases

**Comment by qanadin** [comment]
Okay the issue was a user issue, more importantly how it was being downloaded and auto extracted by safari on MacOS.
