### ISSUE TITLE
No longer able to edit loading zones on certain trailers after they're purchased and trying to buy another of the same kind.

### ISSUE THREAD

**Issue by Luscion** [loki79uk/FS25_UniversalAutoload#4]
I've tried this on multiple trailers, I'm able to edit the loading zones of certain trailers if i havent purchased it from the store as yet but once its purchased and i go back into the shop for the same trailer, the ability to edit the loading zones is gone, at least visibly. Even if i sell both the first trailer and/or the ones bought after i still cannot edit the loading zones anymore in the shop. Problem persists even after deleting saved game and starting a new one.

Trailers affected for me: PWO 24, DPW 1800, Renown Drop Deck

PWO 24 after purchasing the first one  -
 ![TrailerAfterPurchase](https://github.com/user-attachments/assets/2f3cd0f5-ef6e-44c0-85df-9fee9bdb95bb)

Steel Drop Deck after purchasing first one (still works) -
![TrailerAfterPurchase2](https://github.com/user-attachments/assets/3aa88753-95ec-47ee-b24e-15f682df8099)

**Comment by geeknessfr** [comment]
I just tested it on my side. I bought several different trailers, one by one, and had no issues returning to the shop for the same trailer each time, until I got to the PWO 24. For that one, the AutoLoad area was very narrow in height, so I modified it to make it larger.

I bought the trailer (PWO 24) and, at the same time, I purchased the Profi Liner, which already had the correct AutoLoad area. I left the shop and was able to use both trailers without any issues.

However, when I returned to the shop, both the PWO 24 and the Profi Liner no longer had the AutoLoad area, and I got the following in the log:

`2024-11-28 06:56 UniversalAutoload - supported vehicle: Farmtech DPW 1800 - UAL #2718616 #ALL (UNIQUE)
2024-11-28 06:56 *** USING CONFIG FROM SETTINGS - ALL for #ALL (UNIQUE) ***
2024-11-28 06:56 *** NO MATCHING LOCAL CONFIG - #ALL (UNIQUE) ***
2024-11-28 06:56 CREATE SHOP VEHICLE: Farmtech DPW 1800 - UAL #2718616
2024-11-28 06:56 findTensionBelts
2024-11-28 06:56 findLoadingSurface
2024-11-28 06:56 expandLoadingSurface
2024-11-28 06:56 SET HEIGHT
2024-11-28 06:56 INIT SHOP CONFIG
2024-11-28 06:56 DELETE SHOP VEHICLE: Farmtech DPW 1800 - UAL #2718616
2024-11-28 06:56 UniversalAutoload - supported vehicle: Kröger PWO 24 - UAL #2720608 #1 (Apparence 1)
2024-11-28 06:56 Error: Running LUA method 'update'.
C:/Users/PC/Documents/My Games/FarmingSimulator2025/mods/FS25_UniversalAutoload/UniversalAutoload.lua:1282: attempt to index number with 'split'
2024-11-28 06:57 UniversalAutoload - supported vehicle: KRONE Trailer Profi Liner - UAL #2722835 #1 (Krone)
2024-11-28 06:57 Error: Running LUA method 'update'.
C:/Users/PC/Documents/My Games/FarmingSimulator2025/mods/FS25_UniversalAutoload/UniversalAutoload.lua:1282: attempt to index number with 'split'
`

The DPW 1800 mentionned in log worked perfectly, then I selected the PWO 24 and Profi Liner.

**Comment by loki79uk** [comment]
Thanks, I see the problem in the log. Will try to reproduce, but can see I just need to handle the case where the id is a number (not a string).  Nice complete bug report, thank you!

**Comment by loki79uk** [comment]
So git hub auto-closed this bug because I used the words "fixed" in reference to it..  But it should be fixed so will leave closed.   Please re-open if any similar issues with https://github.com/loki79uk/FS25_UniversalAutoload/releases/tag/v0.0.0.2
