### ISSUE TITLE
v0.0.0.8 International CV series big bags clip

### ISSUE THREAD

**Issue by yorgov** [loki79uk/FS25_UniversalAutoload#47]
Hi, currently using v0.0.0.8
When loading big bags (of solid fertilizer in my case) on the the International CV series vehicle, that is configured as a flatbed, the bags load 3 per row, which causes them to clip into each other, which in case causes the games physics to be very sad. In order to express that frustration the physics engine tries to flip my truck around.

Also there are some additional options (maybe left over from debugging)
![image](https://github.com/user-attachments/assets/0c026345-a4dd-426b-a355-a4dbcb520863)

Awesome mod, thank you for the hard work.

**Comment by loki79uk** [comment]
Oh damn, I left those in - let me update the release! :D

**Comment by loki79uk** [comment]
Should be fixed in 0.0.0.9!  Sorry about that. :)

**Comment by yorgov** [comment]
With the risk of being obnoxious the fix is just for the extra UI elements or for the big bags as well.

**Comment by loki79uk** [comment]
Sorry, was just doing screenshots - you can go into the workshop and edit the zone in slightly:
- middle mouse click
- hold ALT and right cliick drag one of the side points to keep centred:
![image](https://github.com/user-attachments/assets/a490d4d9-e272-415d-a04f-519beada8276)

**Comment by loki79uk** [comment]
You have to change something to activate the "customise" button, but it can just be one letter on the number plate.

**Comment by loki79uk** [comment]
Then fits big bags 2 wide:
![image](https://github.com/user-attachments/assets/ec4c9284-2557-4d33-a430-9cd8d8b85b6e)

**Comment by yorgov** [comment]
Awesome, thanks man.
I'll close this one.

**Comment by Snowlx94** [comment]
hey there , i cant load any pallet in my trailer it says all the time theres nothing .. i tried to move them but still not working 
![Bild_2024-12-02_132247618](https://github.com/user-attachments/assets/f1b224ba-4d40-4f1c-bfc8-7b10f482ee8f)
