### ISSUE TITLE
Faces Colour

### ISSUE THREAD

**Issue by jufcar** [loki79uk/FS25_UniversalAutoload#5]
Thanks for getting this great mod working so fast.

In my game metal faces are often very bright due to reflection, as i was experimenting with the new function of this mod i didn't see the triggers for moving the faces at first at all.
It would be nice to change the colour of the small violett dots or make them a bit more saturated for better visibility.
![grafik](https://github.com/user-attachments/assets/27af6975-412f-46a9-82a3-856b8ed22614)

**Comment by loki79uk** [comment]
Thanks for the feedback, I agree it is hard to see them there.  They turn brighter on mouse over, so the idea was to make the transition nice and clear.  I'll reduce the transparancy for now, but once I get a menu working for the options the overlay colours could even be customisable.

**Comment by loki79uk** [comment]
I was originally thinking about making this a setting, but that seems a bit overkill.  What do you think about this change:

Current (0.1)
![image](https://github.com/user-attachments/assets/731bded3-ae0d-43ea-a788-280d2a993a8d)

Proposed (0.5)
![image](https://github.com/user-attachments/assets/a0f54d32-21a2-4f6d-a290-27794569d27b)

It messes with the relative brightness of the hover-over colour, but I can change that too.

**Comment by loki79uk** [comment]
> Sorry for the late reply, i think the last change with 0.5 would be the better option.

Not late at all, I only posted this today.  The one for the base is different, but that is because it appears behind the actual trailer surface, which is useful as it helps to determine if you are above or below the correct level.

**Comment by jufcar** [comment]
I didn't check the header of your comments and thought i forgot to answer.

I think it's fine, that the one at the bottom is different, my problem was specifically with the ones on the left, right and top, which aren't that good to see in my picture and a more saturated colour, like in your pictures help finding them.

This isn't that important for users familiar with this (new) feature of your mod, but i think it would help new users.

**Comment by loki79uk** [comment]
Try the latest release - I realise it is very subjective and depends on monitor resolution, settings, colour of vehicle, etc..  Happy to adjust again if anyone is still having trouble.  The only thing I can't change is the size, since this is fixed by GIANTS.
