### ISSUE TITLE
cant load pallets in last version (multiplayer)

### ISSUE THREAD

**Issue by Snowlx94** [loki79uk/FS25_UniversalAutoload#53]
hey there , i cant load any pallet in my trailer it says all the time theres nothing .. i tried to move them but still not working 
![pallets](https://github.com/user-attachments/assets/f49bee2c-4467-4e6a-9f5f-b448a3d3430a)

**Comment by Exitera** [comment]
Exactly this problem we have already reported to 0.0.0.4 but is unfortunately ignored which I find a pity, this error message is also displayed globally every player on the server sees it

**Comment by loki79uk** [comment]
> Exactly this problem we have already reported to 0.0.0.4 but is unfortunately ignored which I find a pity, this error message is also displayed globally every player on the server sees it

LOL, Are you actually serious?   I am doing this as a hobby.  I have a full time job, a full time life, two kids that have to attend school, cook for, etc.  I have 4 active mods that I'm converting from FS22 to FS25.  I have no documentation for the changes from GIANTS and I have been putting in 5+ hours a day since release.  Yesterday alone I closed about 20 bugs.  I can only go so fast.

I'm really sorry that I didn't reply to your one bug out of 47, or rather didn't get around to it yet...  It sounds to me like you are not ready to use a DEVELOPMENT build of anything.  If you just wait a few months then it will be out on ModHub, hopefully bug free..

**Comment by loki79uk** [comment]
> hey there , i cant load any pallet in my trailer it says all the time theres nothing .. i tried to move them but still not working ![pallets](https://private-user-images.githubusercontent.com/190368001/391540725-f49bee2c-4467-4e6a-9f5f-b448a3d3430a.png?

Hi, please ingore my respone to the other guy.

Can you please:
1) Delete the UniversalAutoload.xml file in your mod settings folder
2) Install the latest version if you have not already
3) try again, and then attach your log to this bug if it is still not working

**Comment by loki79uk** [comment]
Ahh, okay - I didn't realise you were on MP.  I will add a console command to clear the settings from the server.  I will also see if I can find a workaround from in the game.

**Comment by Snowlx94** [comment]
no problem mate. take your time :)

**Comment by loki79uk** [comment]
I have not tested on MP, but I tried to reproduce what I think is the issue in SP.

There is some bug that caused (or still causes) the loadingArea entry to not be written in the settings file.  I don't know if this was from an old version or if it still happens, and I have never re-produced it on my machine.  I have simulated it by removing the line namually in notepad:
![BEFORE](https://github.com/user-attachments/assets/ec2c59e7-7e8b-4f01-a856-98951bc9902d)

Anyway, so with this line missing the loading zone also dissapears, and with it the triggers. As of the latest version, it will look like this in the debugging view (debugging view available in SP only, so this makes MP harder to debug):
![Missing Loading Zone](https://github.com/user-attachments/assets/3fcde884-77d1-4f20-83fc-d4fb9c1a4626)

Now, if you go to the workshop, change the numberplate, reset the zone and apply the new customisation then it should overwite the file with the new setting:

![Change Number Plate](https://github.com/user-attachments/assets/075a63a7-0a1e-4803-9c4f-b2ca3c7908b6)

![Customise](https://github.com/user-attachments/assets/9b19a4c0-d432-462a-8196-831a72e15a19)

![AFTER](https://github.com/user-attachments/assets/a42b1c05-75b0-447a-b9c5-b0949760f63c)


Then, for the rest of that game, reloading the save game or any new games it should work again:
![Restored](https://github.com/user-attachments/assets/d47b9559-c549-4e27-9aff-5c9c6ef22632)
![Restored2](https://github.com/user-attachments/assets/ceb985a5-3a0f-43c6-8300-0bca6d333e66)

**Comment by loki79uk** [comment]
If it is not that, then it is the same explanation as in this bug:
https://github.com/loki79uk/FS25_UniversalAutoload/issues/60

**Comment by loki79uk** [comment]
Okay, sorry, I'm being thick - it is of course the second one (#60) because you get the error that it is full.

I had already started taking the screenshots for the explanation and my brain got confused.  I'll leave them there for now to reference in other bugs if needed.

I'll try to reproduce that now, and add some workarounds to try and prevent it from happening.  The big risk is the opposite problem which results in loading an already loaded trailer.  i.e. https://github.com/loki79uk/FS25_UniversalAutoload/issues/9

**Comment by Snowlx94** [comment]
ok.. now im confused :D is it now the second one ? because i dont get the error that my trailer is full , i got the error that he cant find any containers to load

**Comment by loki79uk** [comment]
> ok.. now im confused :D is it now the second one ? because i dont get the error that my trailer is full , i got the error that he cant find any containers to load

lol, we are both confused!  It could be neither of those.  I have 10 different chats and bugs on the go at the moment and trying to actually write code at the same time, lol.

Have you ever loaded them before, or have those pallets never loaded?  It could be something about the specific pallets.  Can you also check if you have any loading filters set - like "full only", or a specific pallet type?

**Comment by Snowlx94** [comment]
ye i got the filters and if i hit the button to change one of thoose it said to me theres noting :D i moved the pallets to get new pallets

**Comment by loki79uk** [comment]
I just realised that maybe this is the same issue as https://github.com/loki79uk/FS25_UniversalAutoload/issues/69

Does it work properly after a server restart?  Otherwise I still don't know.

**Comment by Snowlx94** [comment]
i tried to understand the solution in #69 but i dont understand :D i restarted the server 3 or 4 times

**Comment by loki79uk** [comment]
> i tried to understand the solution in #69 but i dont understand :D i restarted the server 3 or 4 times

If you restarted and still happening, then it is not that.  Can you attach your mod settings xml so that I can try to reproduce.

**Comment by Snowlx94** [comment]
![image](https://github.com/user-attachments/assets/2cc97b45-1263-4f22-9bb8-f3837b3e320c)

its working finally . i need to put the " old " pallets by myself into the trailer but the new pallets are now moving into the trailer :) i guess your update last night fixed it

**Comment by Snowlx94** [comment]
its kinda tricky to get them but it works for now :D

**Comment by loki79uk** [comment]
Okay, I'm glad it is working for you - I suspect it was something to do with the "trailer full" or "load area full" flags getting out of sync in that case.

If you are on MP and you only just configured it, then the load areas will probably be too small.  Restart server or edit in the shop should work as a workaround: https://github.com/loki79uk/FS25_UniversalAutoload/issues/69

I really need to get the MP debugging display to work, as that will really help with this kind of thing.

**Comment by Snowlx94** [comment]
thank u for help me, u do a great job there :)

**Comment by loki79uk** [comment]
Could actually be fixed now **fingers crossed emoji**
https://github.com/loki79uk/FS25_UniversalAutoload/releases

**Comment by Snowlx94** [comment]
it works perfect ! 

thanks for your work ♥

**Comment by Snowlx94** [comment]
so we can close it :) thaaaank you

**Comment by loki79uk** [comment]
I think this same bug has been in FS22 version the whole time, but it didn't matter because I had a collision test to see if the trailer was actually empty.

**Comment by Be-Mann** [comment]
I also have the problem that I can't load in multiplayer, so I didn't want to open a new issue. I have also just tested again with v0.0.0.14.

As a test object I used the Krone ProfiLiner and tried to load with “prefabricated walls”, “wood chips” and “seedlings”, both an existing and a new ProfiLiner.

I had activated the debug as far as possible and here is the log and the config

[server_log_2024-12-05_00-44-51.txt](https://github.com/user-attachments/files/18015548/log_2024-12-05_00-44-51.txt)
[client_log.txt](https://github.com/user-attachments/files/18015557/log.txt)
[UniversalAutoload.xml.txt](https://github.com/user-attachments/files/18015550/UniversalAutoload.xml.txt)

**Comment by loki79uk** [comment]
> I also have the problem that I can't load in multiplayer, so I didn't want to open a new issue. I have also just tested again with v0.0.0.14. The message that comes up is warning_UNIVERSALAUTOLOAD_NO_OBJECTS_FOUND
> 
> As a test object I used the Krone ProfiLiner and tried to load with “prefabricated walls”, “wood chips” and “seedlings”, both an existing and a new ProfiLiner. The pads were free standing, so nothing that would have blocked.
> 
> I had activated the debug as far as possible and here is the log and the config
> 
> [server_log_2024-12-05_00-44-51.txt](https://github.com/user-attachments/files/18015548/log_2024-12-05_00-44-51.txt) [client_log.txt](https://github.com/user-attachments/files/18015557/log.txt) [UniversalAutoload.xml.txt](https://github.com/user-attachments/files/18015550/UniversalAutoload.xml.txt)

So you have this error in the log:
`Script error in delete: Unknown entity id 369343 for 'object' in method 'delete'.`

I don't understand how that can happen, but it was in a pervious bug too: https://github.com/loki79uk/FS25_UniversalAutoload/issues/56

If anyone can find a way to reproduce this then I stand a better chance of fixing it!

**Comment by Be-Mann** [comment]
Since it was like this on our server with all tests, I can make it possible for you to have a look around if that helps, both the log and ingame

**Comment by loki79uk** [comment]
> Since it was like this on our server with all tests, I can make it possible for you to have a look around if that helps, both the log and ingame

I made a new issue to track this: https://github.com/loki79uk/FS25_UniversalAutoload/issues/85

**Comment by jessedubbink** [comment]
@loki79uk just so you know, most of us appreciate that you are putting in the work you do. Makes our gameplay experience a lot smoother 😁
