### ISSUE TITLE
v0.0.0.9 - Controls after using UAL trailer

### ISSUE THREAD

**Issue by xpedicion** [loki79uk/FS25_UniversalAutoload#54]
I delivered some pallets to sell then switched to a harvester to do a contract. I forgot whether I watered my rice fields so I jumped to one of them. I had the UAL context menu options active on foot and I could not interact with the pump at all. Had to save and reload to fix this.

**Comment by loki79uk** [comment]
I thought I had removed all of the on foot stuff from 22, but clearly not.  Can you attach your log file as this should not happen.
