### ISSUE TITLE
lot of Call Stack spam , on game exit in log file

### ISSUE THREAD

**Issue by Tycoonspaceman** [loki79uk/FS25_UniversalAutoload#56]
Script error in delete: Unknown entity id 322774 for 'object' in method 'delete'.

LUA call stack:
  =[C]:-1 delete
  =dataS/scripts/materials/MotionPathEffectManager.lua:337 unloadMapData
  =dataS/scripts/FSBaseMission.lua:318 delete
  =dataS/scripts/utils/Utils.lua:579 
  =dataS/scripts/mission00.lua:137 delete
  =dataS/scripts/menu.lua:119 OnInGameMenuMenu
  =dataS/scripts/gui/InGameMenu.lua:496 leaveCurrentGame
  =dataS/scripts/gui/InGameMenu.lua:962 onYesNoEnd
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:140 sendCallback
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:197 onYes
  =dataS/scripts/gui/elements/GuiElement.lua:1631 raiseCallback
  =dataS/scripts/gui/elements/ButtonElement.lua:902 sendAction
  =dataS/scripts/gui/elements/ButtonElement.lua:488 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/base/Gui.lua:693 mouseEvent
  =dataS/scripts/events.lua:40 mouseEvent
2024-12-02 14:03 
Script error in delete: Unknown entity id 322777 for 'object' in method 'delete'.

LUA call stack:
  =[C]:-1 delete
  =dataS/scripts/materials/MotionPathEffectManager.lua:337 unloadMapData
  =dataS/scripts/FSBaseMission.lua:318 delete
  =dataS/scripts/utils/Utils.lua:579 
  =dataS/scripts/mission00.lua:137 delete
  =dataS/scripts/menu.lua:119 OnInGameMenuMenu
  =dataS/scripts/gui/InGameMenu.lua:496 leaveCurrentGame
  =dataS/scripts/gui/InGameMenu.lua:962 onYesNoEnd
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:140 sendCallback
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:197 onYes
  =dataS/scripts/gui/elements/GuiElement.lua:1631 raiseCallback
  =dataS/scripts/gui/elements/ButtonElement.lua:902 sendAction
  =dataS/scripts/gui/elements/ButtonElement.lua:488 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/base/Gui.lua:693 mouseEvent
  =dataS/scripts/events.lua:40 mouseEvent
2024-12-02 14:03 
Script error in delete: Unknown entity id 322780 for 'object' in method 'delete'.

LUA call stack:
  =[C]:-1 delete
  =dataS/scripts/materials/MotionPathEffectManager.lua:337 unloadMapData
  =dataS/scripts/FSBaseMission.lua:318 delete
  =dataS/scripts/utils/Utils.lua:579 
  =dataS/scripts/mission00.lua:137 delete
  =dataS/scripts/menu.lua:119 OnInGameMenuMenu
  =dataS/scripts/gui/InGameMenu.lua:496 leaveCurrentGame
  =dataS/scripts/gui/InGameMenu.lua:962 onYesNoEnd
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:140 sendCallback
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:197 onYes
  =dataS/scripts/gui/elements/GuiElement.lua:1631 raiseCallback
  =dataS/scripts/gui/elements/ButtonElement.lua:902 sendAction
  =dataS/scripts/gui/elements/ButtonElement.lua:488 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/base/Gui.lua:693 mouseEvent
  =dataS/scripts/events.lua:40 mouseEvent
2024-12-02 14:03 
Script error in delete: Unknown entity id 322783 for 'object' in method 'delete'.

LUA call stack:
  =[C]:-1 delete
  =dataS/scripts/materials/MotionPathEffectManager.lua:337 unloadMapData
  =dataS/scripts/FSBaseMission.lua:318 delete
  =dataS/scripts/utils/Utils.lua:579 
  =dataS/scripts/mission00.lua:137 delete
  =dataS/scripts/menu.lua:119 OnInGameMenuMenu
  =dataS/scripts/gui/InGameMenu.lua:496 leaveCurrentGame
  =dataS/scripts/gui/InGameMenu.lua:962 onYesNoEnd
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:140 sendCallback
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:197 onYes
  =dataS/scripts/gui/elements/GuiElement.lua:1631 raiseCallback
  =dataS/scripts/gui/elements/ButtonElement.lua:902 sendAction
  =dataS/scripts/gui/elements/ButtonElement.lua:488 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/base/Gui.lua:693 mouseEvent
  =dataS/scripts/events.lua:40 mouseEvent
2024-12-02 14:03 
Script error in delete: Unknown entity id 322786 for 'object' in method 'delete'.

LUA call stack:
  =[C]:-1 delete
  =dataS/scripts/materials/MotionPathEffectManager.lua:337 unloadMapData
  =dataS/scripts/FSBaseMission.lua:318 delete
  =dataS/scripts/utils/Utils.lua:579 
  =dataS/scripts/mission00.lua:137 delete
  =dataS/scripts/menu.lua:119 OnInGameMenuMenu
  =dataS/scripts/gui/InGameMenu.lua:496 leaveCurrentGame
  =dataS/scripts/gui/InGameMenu.lua:962 onYesNoEnd
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:140 sendCallback
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:197 onYes
  =dataS/scripts/gui/elements/GuiElement.lua:1631 raiseCallback
  =dataS/scripts/gui/elements/ButtonElement.lua:902 sendAction
  =dataS/scripts/gui/elements/ButtonElement.lua:488 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/base/Gui.lua:693 mouseEvent
  =dataS/scripts/events.lua:40 mouseEvent
2024-12-02 14:03 
Script error in delete: Unknown entity id 322789 for 'object' in method 'delete'.

LUA call stack:
  =[C]:-1 delete
  =dataS/scripts/materials/MotionPathEffectManager.lua:337 unloadMapData
  =dataS/scripts/FSBaseMission.lua:318 delete
  =dataS/scripts/utils/Utils.lua:579 
  =dataS/scripts/mission00.lua:137 delete
  =dataS/scripts/menu.lua:119 OnInGameMenuMenu
  =dataS/scripts/gui/InGameMenu.lua:496 leaveCurrentGame
  =dataS/scripts/gui/InGameMenu.lua:962 onYesNoEnd
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:140 sendCallback
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:197 onYes
  =dataS/scripts/gui/elements/GuiElement.lua:1631 raiseCallback
  =dataS/scripts/gui/elements/ButtonElement.lua:902 sendAction
  =dataS/scripts/gui/elements/ButtonElement.lua:488 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/base/Gui.lua:693 mouseEvent
  =dataS/scripts/events.lua:40 mouseEvent
2024-12-02 14:03 
Script error in delete: Unknown entity id 323436 for 'object' in method 'delete'.

LUA call stack:
  =[C]:-1 delete
  =dataS/scripts/materials/MotionPathEffectManager.lua:344 unloadMapData
  =dataS/scripts/FSBaseMission.lua:318 delete
  =dataS/scripts/utils/Utils.lua:579 
  =dataS/scripts/mission00.lua:137 delete
  =dataS/scripts/menu.lua:119 OnInGameMenuMenu
  =dataS/scripts/gui/InGameMenu.lua:496 leaveCurrentGame
  =dataS/scripts/gui/InGameMenu.lua:962 onYesNoEnd
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:140 sendCallback
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:197 onYes
  =dataS/scripts/gui/elements/GuiElement.lua:1631 raiseCallback
  =dataS/scripts/gui/elements/ButtonElement.lua:902 sendAction
  =dataS/scripts/gui/elements/ButtonElement.lua:488 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/base/Gui.lua:693 mouseEvent
  =dataS/scripts/events.lua:40 mouseEvent
2024-12-02 14:03 
Script error in delete: Unknown entity id 322793 for 'object' in method 'delete'.

LUA call stack:
  =[C]:-1 delete
  =dataS/scripts/materials/MotionPathEffectManager.lua:344 unloadMapData
  =dataS/scripts/FSBaseMission.lua:318 delete
  =dataS/scripts/utils/Utils.lua:579 
  =dataS/scripts/mission00.lua:137 delete
  =dataS/scripts/menu.lua:119 OnInGameMenuMenu
  =dataS/scripts/gui/InGameMenu.lua:496 leaveCurrentGame
  =dataS/scripts/gui/InGameMenu.lua:962 onYesNoEnd
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:140 sendCallback
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:197 onYes
  =dataS/scripts/gui/elements/GuiElement.lua:1631 raiseCallback
  =dataS/scripts/gui/elements/ButtonElement.lua:902 sendAction
  =dataS/scripts/gui/elements/ButtonElement.lua:488 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/base/Gui.lua:693 mouseEvent
  =dataS/scripts/events.lua:40 mouseEvent
2024-12-02 14:03 
Script error in delete: Unknown entity id 322794 for 'object' in method 'delete'.

LUA call stack:
  =[C]:-1 delete
  =dataS/scripts/materials/MotionPathEffectManager.lua:344 unloadMapData
  =dataS/scripts/FSBaseMission.lua:318 delete
  =dataS/scripts/utils/Utils.lua:579 
  =dataS/scripts/mission00.lua:137 delete
  =dataS/scripts/menu.lua:119 OnInGameMenuMenu
  =dataS/scripts/gui/InGameMenu.lua:496 leaveCurrentGame
  =dataS/scripts/gui/InGameMenu.lua:962 onYesNoEnd
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:140 sendCallback
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:197 onYes
  =dataS/scripts/gui/elements/GuiElement.lua:1631 raiseCallback
  =dataS/scripts/gui/elements/ButtonElement.lua:902 sendAction
  =dataS/scripts/gui/elements/ButtonElement.lua:488 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/base/Gui.lua:693 mouseEvent
  =dataS/scripts/events.lua:40 mouseEvent
2024-12-02 14:03 
Script error in delete: Unknown entity id 322795 for 'object' in method 'delete'.

LUA call stack:
  =[C]:-1 delete
  =dataS/scripts/materials/MotionPathEffectManager.lua:344 unloadMapData
  =dataS/scripts/FSBaseMission.lua:318 delete
  =dataS/scripts/utils/Utils.lua:579 
  =dataS/scripts/mission00.lua:137 delete
  =dataS/scripts/menu.lua:119 OnInGameMenuMenu
  =dataS/scripts/gui/InGameMenu.lua:496 leaveCurrentGame
  =dataS/scripts/gui/InGameMenu.lua:962 onYesNoEnd
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:140 sendCallback
  =dataS/scripts/gui/dialogs/YesNoDialog.lua:197 onYes
  =dataS/scripts/gui/elements/GuiElement.lua:1631 raiseCallback
  =dataS/scripts/gui/elements/ButtonElement.lua:902 sendAction
  =dataS/scripts/gui/elements/ButtonElement.lua:488 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/elements/GuiElement.lua:709 mouseEvent
  =dataS/scripts/gui/base/Gui.lua:693 mouseEvent
  =dataS/scripts/events.lua:40 mouseEvent

**Comment by loki79uk** [comment]
What were you doing at the time?  Can you attach a full log, or at least the first part up to where it starts spamming.  I never delete anything with UAL, so this is likely to be a mod conflict with another mod that does delete something.  OR possibly a base game issue if maybe a sell point is trying to sell a pallet while it is removed from physics?

**Comment by Tycoonspaceman** [comment]
your right its a base game issue , sorry :D . loving this mod by the way , nothing to see here move along!
