### ISSUE TITLE
Messages are sent server-wide to all players

### ISSUE THREAD

**Issue by woeller** [loki79uk/FS25_UniversalAutoload#59]
In MP when loading trailers, we noticed that messages, such as when a trailer is full and nothing else can be loaded, are also sent to other players. Version 0.0.0.9

**Comment by loki79uk** [comment]
Thanks, I forgot about this one.  I think it was the case in FS22 as well, but I will see if I can prevent it.

**Comment by FarmerTreanor** [comment]
Don't remember if your Loaded did show on FS22 globally do remember if selling items and wrong place that would show to everyone.

**Comment by loki79uk** [comment]
All messages use the same code, so it should be all or none.  I think it was one of those bugs that I kept meaning to fix and never did.  But my memoery is not what it used to be!

**Comment by loki79uk** [comment]
So I did prevent it in FS22, but looks like "g_localPlayer:getIsInVehicle(self)" does not do what I thought it did.  It actually just means you are in ANY vehicle, and doesn't take an argument.  I should have used  `g_localPlayer:getCurrentVehicle()` instead.  Will be fixed in next update.

**Comment by loki79uk** [comment]
Can anyone confirm if this is fixed now? I don't have any friends to test :P

**Comment by loki79uk** [comment]
Closing as fixed.  If still getting messages for all players, please re-open or create a new bug.

**Comment by woeller** [comment]
Can confirm, it's fixed. Thank you!
