### ISSUE TITLE
autoload wood trailer

### ISSUE THREAD

**Issue by sschiebrel** [loki79uk/FS25_UniversalAutoload#61]
i'm sure this is on the list.. but while you can configure the autoload box on a wood trailer, it doesn't recognize wood (cut logs) as a valid pickup commodity.

**Comment by geeknessfr** [comment]
As seen on the README, it's already known :)

> PLANNED FEATURES:
> - Menu for global settings (in shop)
> - Set vehicle options in the shop before purchase
> - Bale collection mode (already works with xml edit)
> - ### **Log trailers (can be configured, but do not load anything yet)**
> - Multiplayer synchronisation of ALL settings
> - Show debugging display in multiplayer
> - Custom key bindings

**Comment by sschiebrel** [comment]
sure, like I said, i'm sure it's on the list.. but.    great work guys.. loving it.
