### ISSUE TITLE
Unable to fully load the trailer and also getting a weird message

### ISSUE THREAD

**Issue by FS22fanCatholic** [loki79uk/FS25_UniversalAutoload#66]
Unable to fully load the trailer and also getting a weird message saying: 6585063 ***Load area missing***. The load error message will appear on every vehicle after it appears too

**Comment by geeknessfr** [comment]
Did you get the message with the new version 0.0.0.11 ?

And if yes, could you share you file `log.txt` in `Documents\My Games\FarmingSimulator2025`, please ?

**Comment by loki79uk** [comment]
Which trailer won't fully load?

**Comment by loki79uk** [comment]
I think I've broken layer loading trying to prevent the multi-load area bug!

**Comment by geeknessfr** [comment]
> I think I've broken layer loading trying to prevent the multi-load area bug!

Yes, only one layer loads on it ^^

![image](https://github.com/user-attachments/assets/8dc0d9f8-ee33-4772-9db9-94b82c30808e)

**Comment by loki79uk** [comment]
Should be fixed in latest release!  This is what I get for releasing a new versions on my lunch break and not testing.. :D

**Comment by FS22fanCatholic** [comment]
Okay thank you

**Comment by geeknessfr** [comment]
> Should be fixed in latest release! This is what I get for releasing a new version on my lunch break and not testing.. :D

@loki79uk : Houston.. we have a problem... The layers work..... but don't stop when trailer is fully loaded ^^ 😆 

![image](https://github.com/user-attachments/assets/bee06dc7-1995-46fb-8e1f-7e6b2bf139bf)

**Comment by geeknessfr** [comment]
- Fixed issue, for me, in 0.0.0.13 !
