### ISSUE TITLE
Problema in multiplayer

### ISSUE THREAD

**Issue by Lapos99** [loki79uk/FS25_UniversalAutoload#67]
Ancora oggi non funziona la mod nel multiplayer server dedicato

**Comment by AndriuOfficial** [comment]
Ciao, io ho risolto scaricando il savegame dal dedicato ed inserito in singol player, successivamente acquistato il rimorchio (ricordati di premere la rotella del mouse dove ti esagono dei quadratini rosa) e poi salvato il salvataggio e ricaricato nel dedicato.

**Comment by Lapos99** [comment]
Ma basta che acquisto 1 solo rimorchio o per ogni player deve acquistare il
suo ?

Il giorno mar 3 dic 2024 alle 20:13 AndriuOfficial ***@***.***>
ha scritto:

**Comment by AndriuOfficial** [comment]
@Lapos99 basta che ne acquisti 1, poi gli altri player quando entreranno all'interno della partita anche loro possono usarlo tranquillamente.

**Comment by Lapos99** [comment]
nn posso inserire nuovamente il download nel server

**Comment by loki79uk** [comment]
> Ancora oggi non funziona la mod nel multiplayer server dedicato
> The mod still doesn't work in the dedicated multiplayer server today

It does for me, and for others, so I wonder what you are doing differently?

**Comment by loki79uk** [comment]
Closing as can't reproduce, please re-open if you are still having trouble with the latest version.
