### ISSUE TITLE
231639 *** LOAD AREAS MISSING ***

### ISSUE THREAD

**Issue by Mitchapa** [loki79uk/FS25_UniversalAutoload#71]
Had it working fine with v0.0.0.12. Just updated to v0.0.0.13 and now am getting an error message with the Lizard Dragon that was previously working correctly.

**Comment by loki79uk** [comment]
Can you see the loading zone and triggers with the debug mode on?   If it works, don't worry about it.  It is a warning not an error.

**Comment by geeknessfr** [comment]
> I have multiple errors and can't use the autoloader at all. I can't change the type of container, material or the site of the trailer. Idk if it has to do with the german version of the game but i have a screenshot. I've put the oil on the trailer by hand not with the autoloader. 

Get the latest update of the mod 0.0.0.13, then go to the workshop with your trailer ans see if the loading area is correct, the blue frame box. First change the plate or anything (plate is free), modify the area if needed, then confirm the modification, the trailer should be saved in mod settings.

**Comment by haamic** [comment]
Hello, you wrote "saved in mod settings".
where are the mod settings? Is a special .xml created? Where? In savegame folder?  I can't find the mod settings file. Please tell me where I can find them. Thanks

**Comment by loki79uk** [comment]
"C:\Users\Loki\Documents\My Games\FarmingSimulator2025\modSettings\UniversalAutoload.xml"

**Comment by kaffeebart** [comment]
xxx *** Load Areas Missing *** 
How do i find which vehicle causes the Problem?? As there is only a number i dont know which vehicle it is.

**Comment by loki79uk** [comment]
look further back in the log - it should match when a vehicle was created.  For example I have:
`CREATE REAL VEHICLE: Brantner DD 24073/2 XXL - UAL #404277`

**Comment by Mitchapa** [comment]
> Can you see the loading zone and triggers with the debug mode on? If it works, don't worry about it. It is a warning not an error.

My bad, I saw the warning message and panicked when it stopped working. All I had to do to get it to work again was cycle through the container type and it's back working how it was in the previous version.

**Comment by loki79uk** [comment]
I know it looks scary - but it is just a warning and a debugging tool.  The main purpose is to make people aware that the loading areas CAN dissapear sometimes, so I get more bug reports of things that might not have been noticed otherwise.

**Comment by loki79uk** [comment]
My latest version (to release next has it extracted to a new function:
```lua
function UniversalAutoloadManager.getIsTrainCarriage(vehicle)
	local rootVehicle = vehicle:getRootVehicle()
	if rootVehicle and rootVehicle:getFullName():find("Locomotive")
		or rootVehicle:getFullName():find("Timber Wagon")
		or rootVehicle:getFullName():find("Flatbed Wagon")
		or rootVehicle:getFullName():find("Vehicle Wagon") then
		return true
	end
end
```

**Comment by loki79uk** [comment]
> maybe you can add the EU Train also for your further versions.

Should be fixed now in the latest release https://github.com/loki79uk/FS25_UniversalAutoload/releases

**Comment by HeyPaul1337** [comment]
Ja ich hab den Beitrag gelöscht, weil ich ein eigenes Issue aufgemacht habe.
