### ISSUE TITLE
The UAL mod won't show up v0.0.0.8 and furuther

### ISSUE THREAD

**Issue by Nitron2004** [loki79uk/FS25_UniversalAutoload#73]
The mod won't show up in the downloaded content list since v0.0.0.8. Already tried all the options like extract files from zip and put them in "FS25_UniversalAutoload" folder. Tried every release up to 13. Made sure it was a release but not the code file downloaded.

**Comment by geeknessfr** [comment]
Could you share your file `log.txt` ? It's in `Documents\My Games\FarmingSimulator2025`

Thanks

**Comment by loki79uk** [comment]
You most probably need to update your game to version 1.3.0.0.  Alternatively, edit the moddesc version number from 93 back to 92

**Comment by Nitron2004** [comment]
[log.txt](https://github.com/user-attachments/files/18000254/log.txt)

**Comment by Nitron2004** [comment]
I didn't realise there are an update)) Will try the steps

**Comment by geeknessfr** [comment]
> [log.txt](https://github.com/user-attachments/files/18000254/log.txt)

`ModDesc Version: 92`

As @loki79uk said, you have to update your game, or modify the modDesc.xml in the zip file....

**Comment by Nitron2004** [comment]
Yeah, that's the problem. While didn't have time to update the game the modesc downgrade worked fine. Thank you!
