### ISSUE TITLE
Funzionamento con mezzi a noleggio

### ISSUE THREAD

**Issue by Nanny1990** [loki79uk/FS25_UniversalAutoload#74]
Premetto che la mod è ottima, ma ho notato che con i mezzi a noleggio non funziona (non so se è voluto o meno). Sarebbe possibile attivare questa opzione? Grazie

**Comment by loki79uk** [comment]
Are you on the latest version?  It did this before, but should be working now.  Maybe something has broken again with the latest changes.  I will test again this evening.

**Comment by loki79uk** [comment]
Closing as can't reproduce.  Please re-open if you can provide steps to reproduce with the latest version.
