### ISSUE TITLE
Autoload

### ISSUE THREAD

**Issue by sunshinepower1** [loki79uk/FS25_UniversalAutoload#77]
Hallo, trotz des Links funktioniert der Autoload nicht. Ich habe die Meldung "LOAD AREAS MISSING". Was kann ich noch tun? ich habe unter dem Anhänger einen weißen Würfel. Ich kann ihn aber nicht anders positioniern.

**Comment by Lennart-1337** [comment]
Es handelt sich dabei um bekannte Bugs. Du wirst wohl einfach noch ein wenig Geduld haben müssen bis diese behoben sind

**Comment by loki79uk** [comment]
You need to check your settings file, or delete the whole thing.  See instructions here:
https://github.com/loki79uk/FS25_UniversalAutoload/issues/53#issuecomment-2512476142

**Comment by loki79uk** [comment]
This should all be fixed in the latest version. If you are still having trouble, then first delete your mod settings file and buy the vehicles again (can be in a different savegame).
