### ISSUE TITLE
the mod doesnt load in game,

### ISSUE THREAD

**Issue by Sahadm786** [loki79uk/FS25_UniversalAutoload#79]
i have the latest one downloaded and pasted in the mod folder, but it doesnt show in the game. please help
 
![Screenshot 2024-12-04 214826](https://github.com/user-attachments/assets/7986aab9-07ca-4da4-b409-1a0cd1198692)
![Screenshot 2024-12-04 214800](https://github.com/user-attachments/assets/6d7bfbbd-221f-4c34-9023-4ccc066e705c)
![Screenshot 2024-12-04 214748](https://github.com/user-attachments/assets/f963d547-07f6-4d73-86e7-d1e2cef64c65)
![Screenshot 2024-12-04 214730](https://github.com/user-attachments/assets/4829697c-87d5-48b7-8bb8-f6b725336a5e)

**Comment by Sahadm786** [comment]
just added the screenshot here so that if there are any contradicting mods, please let me knw

**Comment by loki79uk** [comment]
You probably need to install the game update to v1.3.0.0.  A lot of people are having the same issue, I could temporarily downgrade the mod version for the next release.

**Comment by Sahadm786** [comment]
that would be great. Thanks a lot for replying., really appreciate it

**Comment by loki79uk** [comment]
https://github.com/loki79uk/FS25_UniversalAutoload/releases
