### ISSUE TITLE
Not working on Dedicated Server

### ISSUE THREAD

**Issue by sprite1GG** [loki79uk/FS25_UniversalAutoload#8]
I cant make it work on Dedicated Server. I buy the trailer but it says autoloader for Krone Profiliner is disabled.

**Comment by loki79uk** [comment]
Try buying the trailer in a single player game and copy `UniversalAutoload.xml` to the mod settings path on your dedidated server.

Multiplayer is certainly not fully suppoted yet - if anything does work then it is just an accident! :D

**Comment by sprite1GG** [comment]
Thanks, now its working :))

**Comment by Freddy844** [comment]
i do all what you write but my modsettins will not read on the nitrado server with ftp

**Comment by Cyfleche** [comment]
could someone show me or tell me how to copy UniversalAutoload.xml towards the mod settings path on  dedicated server

**Comment by loki79uk** [comment]
> could someone show me or tell me how to copy UniversalAutoload.xml towards the mod settings path on  dedicated server

You shouldn't need to do that anymore with the latest version as settings are sent to the server and saved there as default.  However, if you still need to, you will need to use a program such as WinSCP to send files via FTP.  The server hosting company should give you the connection details.

**Comment by Cyfleche** [comment]
> > could someone show me or tell me how to copy UniversalAutoload.xml towards the mod settings path on  dedicated server
> 
> You shouldn't need to do that anymore with the latest version as settings are sent to the server and saved there as default. However, if you still need to, you will need to use a program such as WinSCP to send files via FTP. The server hosting company should give you the connection details.


ok i will try this with newest updated version
