### ISSUE TITLE
WARNING: load area missing

### ISSUE THREAD

**Issue by criss20ster** [loki79uk/FS25_UniversalAutoload#84]
UniversalAutoload - supported vehicle: Vehicle Wagon - UAL #225755 #ALL (UNIQUE)
2024-12-05 08:33 *** NO LOCAL CONFIGS AVAILABLE - #ALL (UNIQUE) ***
2024-12-05 08:33 CREATE REAL VEHICLE: Vehicle Wagon - UAL #225755
2024-12-05 08:33 Vehicle Wagon - UAL #225755: UAL SETTINGS WERE NOT ADDED
2024-12-05 08:33 INITIALISE UAL VEHICLE (ON LOAD) 225755
2024-12-05 08:33 H:/ModyFS25/FS25_UniversalAutoload/triggers/UniversalAutoloadTriggers.i3d (0.16 ms)
2024-12-05 08:33 WARNING: load area missing - check settings file
2024-12-05 08:33 UAL: ON POST LOAD
2024-12-05 08:33 using xml key - vehicles.vehicle(6).FS25_UniversalAutoload.universalAutoload.currentState

**Comment by criss20ster** [comment]
in that folder you mention, there is no xml file generated 

I understand you that it is only a warning, but the less in the game of this type of messages the better for the game itself

**Comment by loki79uk** [comment]
> in that folder you mention, there is no xml file generated
> 
> I understand you that it is only a warning, but the less in the game of this type of messages the better for the game itself

This is a development version, not the final product.

**Comment by loki79uk** [comment]
If you don't have a settings file then that is the problem it is warning you about.  Can you attach your log please.

**Comment by criss20ster** [comment]
[log.txt](https://github.com/user-attachments/files/18019991/log.txt)

**Comment by loki79uk** [comment]
Could this be a one drive issue?  It says your file was created in:
`C:/Users/criss/OneDrive/Dokumenty/My Games/FarmingSimulator2025/modSettings/UniversalAutoload.xml`

Can you try starting a new savegame and buy a new Vehicle Wagon, then send me the log for that and check if the settings file exists then.

**Comment by loki79uk** [comment]
Sorry, I am rushing to answer bugs before work - that is just a warning that the train is not configured.  It is not a problem at all, I just assumed you were getting the in-game warning message.

**Comment by criss20ster** [comment]
![Desktop 2024-12-05 09-49-07-786](https://github.com/user-attachments/assets/9af5ad61-7216-478d-8441-a9f3a4fef91c)

i don't have this file

**Comment by loki79uk** [comment]
You won't get a file until you actually buy and configure a UAL vehicle.

**Comment by loki79uk** [comment]
I just didn't read your first post properly, it is warning that the train is not configured, but that is totally fine - the train should not be configured yet (I will add it later).

**Comment by criss20ster** [comment]
ok

**Comment by criss20ster** [comment]
Yes I bought a flatbed trailer kroger and sie appeared file, I attach it. But the question is how to select the landing page 

<?xml version="1.0" encoding="utf-8" standalone="no"?>
<universalAutoload>
    <vehicleConfigurations>
        <vehicle configFileName="H:/ModyFS25/FS25_KroegerHKD402_FlatBed/kroegerHKD402.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.004 1.378 -0.785" width="2.400000" length="6.083986" height="2.404678"/>
            </configuration>
        </vehicle>
    </vehicleConfigurations>
</universalAutoload>

**Comment by criss20ster** [comment]
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<universalAutoload>
    <vehicleConfigurations>
        <vehicle configFileName="H:/ModyFS25/FS25_KroegerHKD402_FlatBed/kroegerHKD402.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.004 1.378 -0.785" width="2.400000" length="6.083986" height="2.404678"/>
            </configuration>
        </vehicle>
    </vehicleConfigurations>
</universalAutoload>

**Comment by loki79uk** [comment]
I don't understand what you mean by the landing page?

On the web interface at least, there is a button to attach files:
![image](https://github.com/user-attachments/assets/1994459f-bd22-4d3c-9ddd-fab65ed52af4)

**Comment by criss20ster** [comment]
xml file not supported. i mean the ability to unload to a page whether left or right

**Comment by Winstonsthlm** [comment]
Hi,
I was testing a bit and I also get "Load Areas Missing"  when on foot. 

Have one trailer that support UA and for that it works. Tried clearing the config file and then I get "Load Area Missing" on the trailer since it's not configured which is correct. But the other "Load Area Missing" with different ID I don't know where it's connected to since I get it even on foot.

![Screenshot 2024-12-05 130601](https://github.com/user-attachments/assets/67d9876c-fbb2-4f4c-80fe-84a4b0a7578a)

**Comment by loki79uk** [comment]
That could be a train vehicle I'm not ignoring from another map?  Part of the reason for adding this message is to identify vehicles that have UAL installed that probably shouldn't (i.e. if you didn't buy them!)

**Comment by Winstonsthlm** [comment]
Ah could be, I'm on Zielonka. I guess "Vehicle Wagon" is the train cart.

2024-12-05 13:37 UniversalAutoload - supported vehicle: Vehicle Wagon - UAL #226421 #ALL (UNIQUE)
2024-12-05 13:37 *** NO LOCAL CONFIGS AVAILABLE - #ALL (UNIQUE) ***
2024-12-05 13:37 CREATE REAL VEHICLE: Vehicle Wagon - UAL #226421
2024-12-05 13:37 Vehicle Wagon - UAL #226421: UAL SETTINGS WERE NOT ADDED
2024-12-05 13:37 INITIALISE UAL VEHICLE (ON LOAD) 226421

**Comment by loki79uk** [comment]
I'll add that to the ignore list for now, but in time I will add the trains as well

**Comment by Winstonsthlm** [comment]
By the way, will you later on add a Console Command to reload the config file in game if you manually edit the file? 
Was doing that a lot in FS22 but we didn't have the ability to configure in the shop back then.

**Comment by loki79uk** [comment]
> By the way, will you later on add a Console Command to reload the config file in game if you manually edit the file? Was doing that a lot in FS22 but we didn't have the ability to configure in the shop back then.

Yes, I will add all of the console commands soon.  I just need to get the base loading functionality bug free first!
