### ISSUE TITLE
Default key bind to select Material Type gets overridden when using Stema Trius trailer

### ISSUE THREAD

**Issue by Winstonsthlm** [loki79uk/FS25_UniversalAutoload#86]
Very minor issue

When using trailer "Stema Trius" that use (I think) "Tools Function 3" to open the sides "Change Material Type" will not be visible in help menu or usable. They both use the same default key bind "Y".

Changing the key bind on "Change Material Type" fixes it.

The conflicting key bind also disabled my controller key bind for "Change Material Type" that didn't have a conflict, but that's probably how the game works.

**Comment by loki79uk** [comment]
Thanks - keybindings are a bit of mess..  I would make everything use shift, but it is not ideal because then the key combination takes up too much space and you can't read the text :(

**Comment by loki79uk** [comment]
If you run latest release, you should see some log entries about key conflicts. I can add more cases where I force overriding for certain conflicts.  Let me know what you think.
https://github.com/loki79uk/FS25_UniversalAutoload/releases
