### ISSUE TITLE
Loading Area Missing

### ISSUE THREAD

**Issue by Trijj** [loki79uk/FS25_UniversalAutoload#91]
Using Kroger Trailer. PC Platform. Riverbend. All functions work but this flashing on Upper Left is a bit much.

**Comment by loki79uk** [comment]
This is development version, if you don't want to help develop it then just wait for the release on ModHub.

**Comment by 17goesfast** [comment]
Hello,
I'm using the same trailer on Zielonka, and the palettes are clipping in the trailer.  I've raised the load box in the shop, and I had to add the bale code to the mod setting for this trl.  When I collect bales, they initially sit above the trl  floor at the height I have the load box.  When I hit ctrl-Shift R a 2nd time they sit nicely on the bottom.  Shift R will load bales and they fall through the trl floor.  Thanks for this mod! 
![hi bales](https://github.com/user-attachments/assets/ab849a51-dc4c-4104-aa47-331be552cd27)
![palettes](https://github.com/user-attachments/assets/bc53e2a4-1974-428a-980f-e02a5f591cc9)
![strapped bales](https://github.com/user-attachments/assets/775aa706-4259-4172-9c36-aa327b9dc28a)

**Comment by loki79uk** [comment]
What is that trailer, I've never seen it before?

**Comment by 17goesfast** [comment]
> What is that trailer, I've never seen it before?

It's a Kroeger HKD402 Flat Bed on found of fs25 mods

**Comment by 17goesfast** [comment]
An update great!  TY

**Comment by loki79uk** [comment]
> An update great! TY

You are welcome!

I can't fix this mod trailer though I'm afraid.  The original modder needs to apply the correct collision flags to the surface component.
