### ISSUE TITLE
Steering issues

### ISSUE THREAD

**Issue by WyattLW** [loki79uk/FS25_UniversalAutoload#93]
Hello, i just installed the mod and ran some tests on it.

There's a small issue with some vehicles with integrated load space like "Ape 50", "Lizard Pickup 2017",
I didn't test it but maybe it's in "International Series 200" aswell.

Basically what happens is when it loads stuff in the vehicle, for Ape 50 i had issues i couldn't steer at all unless i moved the pallet a little back.
For the pickup, it kept saying there was an object in front of it when using IA to move it, in particular for the pickup it kept stopping randomly mid-road even after i empty it, maybe the load space itself was somehow blocking.

I think it could be fixed by pushing the loading space outline a bit closer to the back of the vehicle.

**Comment by geeknessfr** [comment]
You can try yourself by editing the area... see the Readme file to know how to and tell us if it's ok then.

Thanks.

**Comment by loki79uk** [comment]
> I think it could be fixed by pushing the loading space outline a bit closer to the back of the vehicle.

This is the whole point of the new FS25 UAL.  In FS22, I spent hours and hours configuring different trailers, and Dan spent even more than me (https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon).  People still complained that it was not wide enough, too low, too high, etc..

So in FS25 every vehicle has a default created by a generic algorithm that works on most trailers, but there will always be some that are not perfect.  You are supposed to configure each trailer exactly how YOU want it!  And as a bonus, I don't have to release updates to configure every new trailer that comes out. :D

**Comment by WyattLW** [comment]
I will give it a shot and report back, but yes, i did read the readme but skipped that part..
Thank you!
