### ISSUE TITLE
Add tags to this GitHub repository

### ISSUE THREAD

**Issue by cloudmaker97** [loki79uk/FS25_UniversalAutoload#95]
I recommend adding tags to this repository for better finding FS25 related stuff on GitHub. Some tags as example:

- https://github.com/topics/fs25
- https://github.com/topics/ls25
- https://github.com/topics/farming-simulator

<details>
<summary>Short tutorial to add tags (click to expand)</summary>

![image](https://github.com/user-attachments/assets/e6a9ea26-2356-4c92-9379-31ab244e444a)
![image](https://github.com/user-attachments/assets/5f00fbeb-8e42-441f-8d78-b06a9acad6e0)
</details>

**Comment by loki79uk** [comment]
Done, thank you!
