### ISSUE TITLE
Autoload wood transport

### ISSUE THREAD

**Issue by Napoleon231187** [loki79uk/FS25_UniversalAutoload#97]
hello 

i thought i try to use this for a contract but unfortunately it doesn't detect the wood  and there for isnt working any ideas ?

**Comment by loki79uk** [comment]
Yes, wood loading has not been added yet.  It is clearly stated in the readme on the front page, and in two other bugs: https://github.com/loki79uk/FS25_UniversalAutoload/issues/61 https://github.com/loki79uk/FS25_UniversalAutoload/issues/45

**Comment by Napoleon231187** [comment]
Oh sry I typed it in the search and nothing come up …. Sent from my iPhoneOn 7 Dec 2024, at 17:41, Loki_79 ***@***.***> wrote:﻿
Yes, wood loading has not been added yet.  It is clearly stated in the readme on the front page, and in two other bugs: #61 #45
